---
permalink: sg6000/accessing-and-configuring-santricity-system-manager.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, SANtricity System Manager, SANtricity, System Manager, configure, configuring, setup, set up, setting up, access, accessing, E-Series AutoSupport, autosupport 
summary: Puede usar System Manager de SANtricity para supervisar el estado de las controladoras de almacenamiento, los discos de almacenamiento y otros componentes de hardware en la bandeja de controladoras de almacenamiento. También puede configurar un proxy para AutoSupport E-Series que permite enviar mensajes de AutoSupport desde el dispositivo sin utilizar el puerto de gestión. 
---
= Acceder y configurar System Manager de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar System Manager de SANtricity para supervisar el estado de las controladoras de almacenamiento, los discos de almacenamiento y otros componentes de hardware en la bandeja de controladoras de almacenamiento. También puede configurar un proxy para AutoSupport E-Series que permite enviar mensajes de AutoSupport desde el dispositivo sin utilizar el puerto de gestión.

.Pasos
* link:setting-up-and-accessing-santricity-system-manager.html["Configuración y acceso a SANtricity System Manager"]
* link:reviewing-hardware-status-in-santricity-system-manager.html["Revisar el estado del hardware en SANtricity System Manager"]
* link:setting-ip-addresses-for-storage-controllers-using-storagegrid-appliance-installer.html["Establecimiento de las direcciones IP de las controladoras de almacenamiento mediante el instalador de dispositivos de StorageGRID"]

