---
permalink: sg6000/configuring-hardware.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: Después de aplicar la alimentación al dispositivo, debe configurar las conexiones de red que utilizará StorageGRID. Es necesario configurar SANtricity System Manager, que es el software que se utilizará para supervisar las controladoras de almacenamiento y otro hardware en la bandeja de controladoras. También debe asegurarse de que puede acceder a la interfaz de BMC para el controlador SG6000-CN. 
---
= Configurar el hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de aplicar la alimentación al dispositivo, debe configurar las conexiones de red que utilizará StorageGRID. Es necesario configurar SANtricity System Manager, que es el software que se utilizará para supervisar las controladoras de almacenamiento y otro hardware en la bandeja de controladoras. También debe asegurarse de que puede acceder a la interfaz de BMC para el controlador SG6000-CN.

.Pasos
* link:configuring-storagegrid-connections.html["Configurar las conexiones StorageGRID"]
* link:accessing-and-configuring-santricity-system-manager.html["Acceder y configurar System Manager de SANtricity"]
* link:configuring-bmc-interface-sg6000.html["Configuración de la interfaz BMC"]
* link:optional-enabling-node-encryption.html["Opcional: Habilitar el cifrado de nodos"]
* link:optional-changing-raid-mode-sg6000-only.html["Opcional: Cambio del modo RAID (sólo SG6000)"]
* link:optional-remapping-network-ports-for-appliance-sg6000.html["Opcional: Reasignación de puertos de red para el dispositivo"]

