---
permalink: sg6000/configuring-bmc-interface-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, sg6000-cn, storage node, storage appliance, BMC, baseboard management controller, configure, setup, set up 
summary: 'La interfaz de usuario del controlador de administración de la placa base \(BMC\) del controlador SG6000-CN proporciona información de estado sobre el hardware y permite configurar los ajustes SNMP y otras opciones para el controlador SG6000-CN.' 
---
= Configuración de la interfaz BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de usuario del controlador de administración de la placa base (BMC) del controlador SG6000-CN proporciona información de estado sobre el hardware y permite configurar los ajustes SNMP y otras opciones para el controlador SG6000-CN.

.Pasos
* link:changing-root-password-for-bmc-interface-sg6000.html["Cambiar la contraseña de root para la interfaz de BMC"]
* link:setting-ip-address-for-bmc-management-port-sg6000.html["Configurar la dirección IP para el puerto de gestión del BMC"]
* link:accessing-bmc-interface-sg6000.html["Acceso a la interfaz del BMC"]
* link:configuring-snmp-settings-for-sg6000-cn-controller.html["Configuración de los ajustes SNMP para el controlador SG6000-CN"]
* link:setting-up-email-notifications-for-alerts.html["Configurar notificaciones por correo electrónico para alertas"]

