---
permalink: sg6000/reviewing-appliance-network-connections-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, network connections, network connection, network, connection, grid, admin, client, bmc, management, SANtricity System Manager, SANtricity 
summary: Antes de instalar el dispositivo StorageGRID, debe saber qué redes se pueden conectar al dispositivo. 
---
= Revisar las conexiones de red del dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar el dispositivo StorageGRID, debe saber qué redes se pueden conectar al dispositivo.

Al implementar un dispositivo de StorageGRID como nodo de almacenamiento en un sistema StorageGRID, puede conectarlo a las siguientes redes:

* *Red de Grid para StorageGRID*: La red de red se utiliza para todo el tráfico interno de StorageGRID. Proporciona conectividad entre todos los nodos de la cuadrícula, en todos los sitios y subredes. Se requiere la red de red.
* *Red de administración para StorageGRID*: La Red de administración es una red cerrada que se utiliza para la administración y el mantenimiento del sistema. La red de administración suele ser una red privada y no es necesario que se pueda enrutar entre sitios. La red administrativa es opcional.
* *Red de clientes para StorageGRID:* la red de clientes es una red abierta que se utiliza para proporcionar acceso a las aplicaciones cliente, incluidos S3 y Swift. La red de cliente proporciona acceso de protocolo de cliente a la cuadrícula, de modo que la red de red de red pueda aislarse y protegerse. La red cliente es opcional.
* *Red de administración para el Administrador del sistema de SANtricity*: Esta red proporciona acceso al Administrador del sistema de SANtricity en la controladora de almacenamiento, lo que le permite supervisar y administrar los componentes de hardware en la bandeja de la controladora de almacenamiento. Esta red de gestión puede ser la misma que la Red de administración para StorageGRID, o bien puede ser una red de gestión independiente.
* *Red de gestión de BMC para el controlador SG6000-CN:* esta red proporciona acceso al controlador de administración de la placa base en el SG6000-CN, lo que le permite supervisar y gestionar los componentes de hardware en el controlador SG6000-CN. Esta red de gestión puede ser la misma que la Red de administración para StorageGRID, o bien puede ser una red de gestión independiente.



NOTE: Para obtener información detallada acerca de las redes StorageGRID, consulte _Grid primer_.

.Información relacionada
link:gathering-installation-information-sg6000.html["Recopilación de información de instalación (SG6000)"]

link:cabling-appliance-sg6000.html["Cableado del dispositivo (SG6000)"]

link:port-bond-modes-for-sg6000-cn-controller.html["Modos de enlace de puertos para el controlador SG6000-CN"]

link:../network/index.html["Directrices de red"]
