---
permalink: audit/audit-message-overview.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, structure, content 
summary: Estas instrucciones contienen información sobre la estructura y el contenido de los mensajes de auditoría y los registros de auditoría de StorageGRID. Esta información se puede utilizar para leer y analizar el registro de auditoría de la actividad del sistema. 
---
= Información general de los mensajes de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas instrucciones contienen información sobre la estructura y el contenido de los mensajes de auditoría y los registros de auditoría de StorageGRID. Esta información se puede utilizar para leer y analizar el registro de auditoría de la actividad del sistema.

Estas instrucciones son para los administradores responsables de generar informes sobre la actividad y el uso del sistema que requieran analizar los mensajes de auditoría del sistema StorageGRID.

Se supone que tiene un conocimiento sólido de la naturaleza de las actividades auditadas dentro del sistema StorageGRID. Para usar el archivo de registro de texto, debe tener acceso al recurso compartido de auditoría configurado en el nodo de administración.

.Información relacionada
link:../admin/index.html["Administre StorageGRID"]
