---
settings:
  name: StorageGRID
  search: storagegrid-enable,storagegrid-115
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  versions:
  - version-number: '11.5'
    url: "/storagegrid-115"
  - version-number: '11.9'
    url: "/storagegrid"
  - version-number: '11.8'
    url: "/storagegrid-118"
  - version-number: '11.7'
    url: "/storagegrid-117"
  - version-number: '11.6'
    url: "/storagegrid-116"
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de StorageGRID 11,5
    url: "/index.html"
  - section: release-notes
  - title: Manos a la obra
    entries:
    - section: primer
    - section: network
  - title: Instale y actualice el software
    entries:
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Instale y mantenga el hardware
    entries:
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Configurar y gestionar
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Utilice StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Supervisión y solución de problemas
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Mantener
    entries:
    - section: expand
    - section: maintain
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
