---
permalink: upgrade/downloading-recovery-package.html 
sidebar: sidebar 
keywords: recovery package, download 
summary: El archivo de paquete de recuperación permite restaurar el sistema StorageGRID en caso de producirse un fallo. 
---
= Descarga del paquete de recuperación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El archivo de paquete de recuperación permite restaurar el sistema StorageGRID en caso de producirse un fallo.

.Lo que necesitará
* Debe iniciar sesión en Grid Manager mediante un explorador compatible.
* Debe tener la clave de acceso de aprovisionamiento.
* Debe tener permisos de acceso específicos.


.Acerca de esta tarea
Descargue el archivo de paquete de recuperación actual antes de realizar cambios en la topología de la cuadrícula en el sistema StorageGRID o antes de actualizar el software. A continuación, descargue una nueva copia del paquete de recuperación después de realizar cambios en la topología de la cuadrícula o después de actualizar el software.

.Pasos
. Seleccione *Mantenimiento* > *sistema* > *paquete de recuperación*.
. Introduzca la frase de acceso de aprovisionamiento y seleccione *Iniciar descarga*.
+
La descarga comienza inmediatamente.

. Cuando finalice la descarga:
+
.. Abra el `.zip` archivo.
.. Confirme que incluye un `gpt-backup` directorio y un interior `.zip` archivo.
.. Extraer el interior `.zip` archivo.
.. Confirme que puede abrir el `Passwords.txt` archivo.


. Copie el archivo del paquete de recuperación descargado (`.zip`) a dos ubicaciones seguras, seguras y separadas.
+

IMPORTANT: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden usar para obtener datos del sistema StorageGRID.



.Información relacionada
link:../admin/index.html["Administre StorageGRID"]
