---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Debe comprender cómo se verá afectado su sistema StorageGRID durante la actualización. 
---
= Cómo se ve afectado el sistema durante la actualización
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe comprender cómo se verá afectado su sistema StorageGRID durante la actualización.



== Las actualizaciones de StorageGRID no son disruptivas

El sistema StorageGRID puede procesar y recuperar datos de las aplicaciones cliente durante el proceso de actualización. Los nodos de grid se ven inactivos de uno en uno durante la actualización, por lo que no hay una hora cuando todos los nodos de grid no están disponibles.

Para permitir la disponibilidad continua, debe asegurarse de que los objetos se almacenen de forma redundante con las políticas de ILM apropiadas. También debe asegurarse de que todos los clientes externos de S3 o Swift estén configurados para enviar solicitudes a una de las siguientes:

* Un extremo de StorageGRID configurado como grupo de alta disponibilidad
* Un equilibrador de carga de terceros de alta disponibilidad
* Múltiples nodos de puerta de enlace para cada cliente
* Varios nodos de almacenamiento para cada cliente




== El firmware del dispositivo se ha actualizado

Durante la actualización de StorageGRID 11.5:

* Todos los nodos de dispositivos StorageGRID se actualizan automáticamente a la versión de firmware 3.5 de StorageGRID Appliance Installer.
* Los dispositivos SG6060 y SGF6024 se actualizan automáticamente a la versión de firmware del BIOS 3B03.EX y a la versión de firmware del BMC 3.90.07.
* Los dispositivos SG100 y SG1000 se actualizan automáticamente a la versión 3B08.EC del firmware del BIOS y a la versión 4.64.07 del firmware del BMC.




== Es posible que se activen alertas

Es posible que se activen alertas cuando se inician y se detienen los servicios y cuando el sistema StorageGRID funciona como un entorno de versiones mixtas (algunos nodos de grid que ejecutan una versión anterior, mientras que otros se han actualizado a una versión posterior). Por ejemplo, es posible que aparezca la alerta *no se puede comunicar con el nodo* cuando se detienen los servicios, o que aparezca la alerta *error de comunicación* de Cassandra cuando algunos nodos se han actualizado a StorageGRID 11.5 pero otros nodos todavía ejecutan StorageGRID 11.4.

En general, estas alertas se borran cuando se completa la actualización.

Una vez completada la actualización, puede revisar cualquier alerta relacionada con la actualización seleccionando *Alertas resueltas recientemente* en el Panel de Grid Manager.


NOTE: Durante la actualización a StorageGRID 11.5, puede activarse la alerta *colocación de ILM inalcanzable* cuando se detienen los nodos de almacenamiento. Esta alerta puede persistir durante 1 día después de que se completó correctamente la actualización.



== Se generan muchas notificaciones SNMP

Tenga en cuenta que es posible que se genere un gran número de notificaciones SNMP cuando se detengan los nodos de grid y se reinician durante la actualización. Para evitar notificaciones excesivas, desactive la casilla de verificación *Activar notificaciones de agente SNMP* (*Configuración* > *Supervisión* > *Agente SNMP*) para desactivar las notificaciones SNMP antes de iniciar la actualización. A continuación, vuelva a habilitar las notificaciones cuando finalice la actualización.



== Los cambios de configuración están restringidos

Hasta que finalice la tarea *Activar nueva función*:

* No realice ningún cambio en la configuración de la cuadrícula.
* No cambie la configuración del nivel de auditoría.
* No active ni desactive ninguna nueva función.
* No actualice la configuración de ILM. De lo contrario, es posible que experimente un comportamiento de ILM inconsistente e inesperado.
* No aplique una revisión ni recupere un nodo de cuadrícula.


Hasta que finalice la tarea *pasos de actualización final*:

* No realice un procedimiento de expansión.
* No realice un procedimiento de retirada de servicio.

