---
permalink: sg100-1000/configuring-bmc-interface-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, BMC, baseboard management controller, configure, setup, set up 
summary: 'La interfaz de usuario del controlador de administración de la placa base \(BMC\) en el dispositivo de servicios proporciona información de estado sobre el hardware y permite configurar los ajustes SNMP y otras opciones para el dispositivo de servicios.' 
---
= Configuración de la interfaz BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de usuario del controlador de administración de la placa base (BMC) en el dispositivo de servicios proporciona información de estado sobre el hardware y permite configurar los ajustes SNMP y otras opciones para el dispositivo de servicios.

.Pasos
* link:changing-root-password-for-bmc-interface-sg1000.html["Cambiar la contraseña de root para la interfaz de BMC"]
* link:setting-ip-address-for-bmc-management-port-sg1000.html["Configurar la dirección IP para el puerto de gestión del BMC"]
* link:accessing-bmc-interface-sg1000.html["Acceso a la interfaz del BMC"]
* link:configuring-snmp-settings-for-sg1000.html["Configuración de los ajustes de SNMP para el dispositivo de servicios"]
* link:setting-up-email-notifications-for-alerts.html["Configurar notificaciones por correo electrónico para alertas"]

