---
permalink: sg100-1000/unable-to-connect-to-appliance-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, troubleshoot, troubleshooting, connect, connection, unable to connect, no connection 
summary: Si no puede conectarse al dispositivo de servicios, puede haber un problema de red o puede que la instalación del hardware no se haya completado correctamente. 
---
= No se puede conectar al dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si no puede conectarse al dispositivo de servicios, puede haber un problema de red o puede que la instalación del hardware no se haya completado correctamente.

.Pasos
. Intente hacer ping al dispositivo con la dirección IP del dispositivo : +
`*ping _services_appliance_IP_*`
. Si no recibe respuesta del ping, confirme que está utilizando la dirección IP correcta.
+
Puede utilizar la dirección IP del dispositivo en la red de grid, la red de administración o la red de cliente.

. Si la dirección IP es correcta, compruebe el cableado del dispositivo, los transceptores QSFP o SFP y la configuración de red.
+
Si esto no se resuelve el problema, póngase en contacto con el soporte técnico.

. Si el ping se ha realizado correctamente, abra un explorador Web.
. Introduzca la URL para el instalador de dispositivos de StorageGRID: +
`*https://_appliances_controller_IP_:8443*`
+
Aparece la página de inicio.


