---
permalink: ubuntu/automating-installation.html 
sidebar: sidebar 
keywords: storagegrid, ubuntu, debian, automating installation, automate installation 
summary: Puede automatizar la instalación del servicio de host de StorageGRID y la configuración de los nodos de grid. 
---
= Automatización de la instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede automatizar la instalación del servicio de host de StorageGRID y la configuración de los nodos de grid.

.Acerca de esta tarea
La automatización de la puesta en marcha puede ser útil en cualquiera de los siguientes casos:

* Ya utiliza un marco de orquestación estándar, como Ansible, Puppet o Chef, para poner en marcha y configurar hosts físicos o virtuales.
* Tiene pensado implementar varias instancias de StorageGRID.
* Está poniendo en marcha una instancia de StorageGRID grande y compleja.


El servicio de host StorageGRID se instala mediante un paquete y está impulsado por archivos de configuración que pueden crearse de forma interactiva durante una instalación manual, o bien se pueden preparar con antelación (o mediante programación) para permitir la instalación automatizada mediante marcos de orquestación estándar. StorageGRID proporciona scripts Python opcionales para automatizar la configuración de dispositivos StorageGRID y todo el sistema StorageGRID (el «grid»). Puede utilizar estos scripts directamente o puede inspeccionarlos para obtener información sobre cómo utilizar la API REST de instalación de StorageGRID en las herramientas de configuración e implementación de grid que desarrolla usted mismo.
