---
permalink: swift/how-storagegrid-implements-swift-rest-api.html 
sidebar: sidebar 
keywords:  
summary: Una aplicación cliente puede usar llamadas API DE REST de Swift para conectarse a nodos de almacenamiento y nodos de puerta de enlace para crear contenedores, así como para almacenar y recuperar objetos. De este modo, las aplicaciones orientadas a los servicios desarrolladas para OpenStack Swift pueden conectarse con el almacenamiento de objetos en las instalaciones que proporciona el sistema StorageGRID. 
---
= Cómo StorageGRID implementa la API DE REST de Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una aplicación cliente puede usar llamadas API DE REST de Swift para conectarse a nodos de almacenamiento y nodos de puerta de enlace para crear contenedores, así como para almacenar y recuperar objetos. De este modo, las aplicaciones orientadas a los servicios desarrolladas para OpenStack Swift pueden conectarse con el almacenamiento de objetos en las instalaciones que proporciona el sistema StorageGRID.



== Gestión de objetos Swift

Una vez que se han ingerido objetos Swift en el sistema StorageGRID, se gestionan con las reglas de gestión de ciclo de vida de la información (ILM) de la política de ILM activa del sistema. Las reglas y políticas de ILM determinan la manera en que StorageGRID crea y distribuye copias de datos de objetos y la manera en que las administra. Por ejemplo, una regla de ILM puede aplicarse a los objetos en contenedores Swift específicos y puede especificar que se guarden varias copias de objetos en varios centros de datos durante un determinado número de años.

Póngase en contacto con su administrador de StorageGRID si necesita comprender cómo las políticas y las reglas de ILM de la cuadrícula afectarán a los objetos de la cuenta de inquilino de Swift.



== Solicitudes de clientes en conflicto

Las solicitudes de clientes en conflicto, como una escritura de dos clientes en la misma clave, se resuelven en base a «'últimas ventas conseguidas'». La programación de la evaluación de «'latest-WINS'» se basa en cuándo el sistema StorageGRID completa una solicitud determinada, y no en cuándo los clientes de Swift inician una operación.



== Garantías y controles de coherencia

De forma predeterminada, StorageGRID proporciona coherencia de lectura tras escritura para los objetos recién creados y coherencia eventual para las actualizaciones de objetos y operaciones DE CABECERA. Cualquier OBTENER después de un PUESTO completado correctamente podrá leer los datos recién escritos. Las sobrescrituras de objetos existentes, actualizaciones de metadatos y eliminaciones son coherentes en la actualidad. Por lo general, las sobrescrituras tardan segundos o minutos en propagarse, pero pueden tardar hasta 15 días.

StorageGRID también le permite controlar la coherencia de cada contenedor. Puede cambiar el control de coherencia para compensar la disponibilidad de los objetos y la coherencia de dichos objetos en diferentes nodos y sitios de almacenamiento, según lo requiera su aplicación.

.Información relacionada
link:../ilm/index.html["Gestión de objetos con ILM"]

link:get-container-consistency-request.html["OBTENGA la solicitud de consistencia del contenedor"]

link:put-container-consistency-request.html["PONGA la solicitud de consistencia del contenedor"]
