---
permalink: network/storagegrid-network-types.html 
sidebar: sidebar 
keywords: storagegrid, network types, grid traffic, admin traffic, client traffic, grid network, admin network, client network 
summary: Los nodos de grid de un sistema de StorageGRID procesan el tráfico de grid, el tráfico de administración y el tráfico de cliente. Debe configurar la red de forma adecuada para administrar estos tres tipos de tráfico y proporcionar control y seguridad. 
---
= Tipos de red StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los nodos de grid en un proceso del sistema de StorageGRID _grid traffic_, _admin traffic_ y _client_. Debe configurar la red de forma adecuada para administrar estos tres tipos de tráfico y proporcionar control y seguridad.



== Tipos de tráfico

[cols="1a,4a,2a"]
|===
| Tipo de tráfico | Descripción | Tipo de red 


 a| 
Tráfico de red
 a| 
El tráfico interno de StorageGRID que viaja entre todos los nodos de la cuadrícula. Todos los nodos de grid deben poder comunicarse con el resto de los nodos de grid en esta red.
 a| 
Red de grid (obligatoria)



 a| 
Tráfico de administración
 a| 
El tráfico utilizado para la administración y el mantenimiento del sistema.
 a| 
Red administrativa (opcional)



 a| 
Tráfico del cliente
 a| 
El tráfico que se desplaza entre aplicaciones cliente externas y la cuadrícula, incluidas todas las solicitudes de almacenamiento de objetos de los clientes S3 y Swift.
 a| 
Red de cliente (opcional)

|===
Puede configurar las redes de las siguientes maneras:

* Sólo red de red de red
* Redes Grid y Admin
* Redes de clientes y grid
* Grid, Admin y redes de clientes


La red de red es obligatoria y puede administrar todo el tráfico de red. Las redes de administración y cliente se pueden incluir en el momento de la instalación o agregar más tarde para adaptarse a los cambios en los requisitos. Aunque la red de administración y la red de cliente son opcionales, cuando se utilizan estas redes para gestionar el tráfico administrativo y de cliente, la red de cuadrícula se puede aislar y proteger.



== Interfaces de red

Los nodos StorageGRID están conectados a cada red de acuerdo con las siguientes interfaces específicas:

|===
| Red | Nombre de la interfaz 


 a| 
Red de grid (obligatoria)
 a| 
eth0



 a| 
Red administrativa (opcional)
 a| 
eth1



 a| 
Red de cliente (opcional)
 a| 
eth2

|===
Para obtener detalles sobre la asignación de puertos virtuales o físicos a interfaces de red de nodos, consulte las instrucciones de instalación.

Tiene que configurar lo siguiente para cada red que habilite en un nodo:

* Dirección IP
* Máscara de subred
* Dirección IP de la pasarela


Solo puede configurar una combinación de dirección IP, máscara y puerta de enlace para cada una de las tres redes de cada nodo de grid. Si no desea configurar una puerta de enlace para una red, debe usar la dirección IP como dirección de puerta de enlace.

Los grupos de alta disponibilidad permiten agregar direcciones IP virtuales a la interfaz de red de Grid o de cliente. Para obtener más información, consulte las instrucciones para administrar StorageGRID.



== Red Grid

Se requiere la red de red. Se utiliza para todo el tráfico interno de StorageGRID. Grid Network proporciona conectividad entre todos los nodos de la cuadrícula, en todos los sitios y subredes. Todos los nodos de la red de cuadrícula deben poder comunicarse con los demás nodos. La red de cuadrícula puede estar compuesta de varias subredes. Las redes que contienen servicios de grid críticos, como NTP, también se pueden agregar como subredes de grid.


NOTE: StorageGRID no admite la traducción de direcciones de red (NAT) entre los nodos.

La red de cuadrícula se puede utilizar para todo el tráfico de administración y todo el tráfico de cliente, incluso si la red de administración y la red de cliente están configuradas. La puerta de enlace de red de cuadrícula es la puerta de enlace predeterminada del nodo a menos que el nodo tenga configurada la red de cliente.


IMPORTANT: Al configurar la red de cuadrícula, debe asegurarse de que la red está protegida de clientes que no son de confianza, como los que se encuentran en Internet abierto.

Tenga en cuenta los siguientes requisitos y detalles de Grid Network:

* La pasarela de red de cuadrícula debe configurarse si hay varias subredes de la cuadrícula.
* Grid Network Gateway es la puerta de enlace predeterminada del nodo hasta que se completa la configuración de la cuadrícula.
* Se generan automáticamente rutas estáticas para todos los nodos a todas las subredes configuradas en la lista global de subredes de red de cuadrícula.
* Si se agrega una red de cliente, la puerta de enlace predeterminada cambia de la puerta de enlace de red de cuadrícula a la puerta de enlace de red de cliente cuando finaliza la configuración de la cuadrícula.




== Red de administración

La red administrativa es opcional. Una vez configurada, se puede utilizar para el tráfico de administración y mantenimiento del sistema. La red administrativa suele ser una red privada y no es necesario que se pueda enrutar entre nodos.

Puede elegir qué nodos de grid deben tener habilitada la red de administrador.

Mediante el uso de una red de administración, el tráfico administrativo y de mantenimiento no necesita desplazarse por la red de red. Los usos típicos de la red de administración incluyen acceso a la interfaz de usuario de Grid Manager, acceso a servicios críticos como NTP, DNS, gestión de claves externa (KMS) y protocolo ligero de acceso a directorios (LDAP), acceso a registros de auditoría en nodos de administración y acceso al protocolo de shell seguro (SSH) para mantenimiento y soporte.

La red de administración nunca se utiliza para el tráfico de grid interno. Se proporciona una puerta de enlace de red de administración y permite que la red de administración se comunique con varias subredes externas. Sin embargo, la puerta de enlace de red del administrador nunca se usa como la puerta de enlace predeterminada del nodo.

Tenga en cuenta los siguientes requisitos y detalles para la red de administración:

* La pasarela de red de administración es necesaria si las conexiones se realizarán desde fuera de la subred de la red de administración o si se configuran varias subredes de la red de administración.
* Se crean rutas estáticas para cada subred configurada en la lista de subredes de red de administración del nodo.




== Red cliente

La red cliente es opcional. Cuando se la configura, se utiliza para proporcionar acceso a los servicios grid para aplicaciones cliente como S3 y Swift. Si piensa hacer que los datos de StorageGRID sean accesibles para un recurso externo (por ejemplo, un pool de almacenamiento en cloud o el servicio de replicación de CloudMirror de StorageGRID), el recurso externo también puede usar la red de clientes. Los nodos de grid pueden comunicarse con cualquier subred accesible a través de la puerta de enlace de red del cliente.

Puede elegir qué nodos de grid deben tener activada la red de cliente. No es necesario que todos los nodos estén en la misma red de cliente y los nodos nunca se comunicarán entre sí a través de la red de cliente. La red de cliente no se pone en funcionamiento hasta que se completa la instalación de la red.

Para mayor seguridad, puede especificar que la interfaz de red de cliente de un nodo no sea de confianza, de modo que la red de cliente sea más restrictiva de la que se permitan las conexiones. Si la interfaz de red de cliente de un nodo no es de confianza, la interfaz acepta conexiones salientes como las que utiliza la replicación de CloudMirror, pero solo acepta conexiones entrantes en puertos que se han configurado explícitamente como extremos de equilibrador de carga. Para obtener más información acerca de la función Red cliente no confiable y el servicio equilibrador de carga, consulte las instrucciones para administrar StorageGRID.

Cuando utiliza una red cliente, no es necesario que el tráfico de cliente se desplace por la red de red de red. El tráfico de red de cuadrícula puede separarse en una red segura que no se puede enrutar. Los siguientes tipos de nodo se configuran con frecuencia con una red de cliente:

* Nodos de puerta de enlace, debido a que estos nodos proporcionan acceso al servicio de equilibrado de carga de StorageGRID y acceso de clientes S3 y Swift a la grid.
* Nodos de almacenamiento, ya que estos nodos proporcionan acceso a los protocolos S3 y Swift, así como a los pools de almacenamiento en cloud y al servicio de replicación de CloudMirror.
* Los nodos de administración, para garantizar que los usuarios inquilinos se puedan conectar al Administrador de inquilinos sin tener que utilizar la red de administración.


Tenga en cuenta lo siguiente para la red de cliente:

* La puerta de enlace de red de cliente es necesaria si la red de cliente está configurada.
* La puerta de enlace de red de cliente se convierte en la ruta predeterminada para el nodo de la cuadrícula cuando finaliza la configuración de la cuadrícula.


.Información relacionada
link:networking-requirements-and-guidelines.html["Directrices y requisitos de red"]

link:../admin/index.html["Administre StorageGRID"]

link:../sg100-1000/index.html["SG100  servicios de aplicaciones SG1000"]

link:../sg6000/index.html["Dispositivos de almacenamiento SG6000"]

link:../sg5700/index.html["Dispositivos de almacenamiento SG5700"]

link:../rhel/index.html["Instale Red Hat Enterprise Linux o CentOS"]

link:../ubuntu/index.html["Instalar Ubuntu o Debian"]

link:../vmware/index.html["Instale VMware"]
