---
permalink: network/storagegrid-networking-overview.html 
sidebar: sidebar 
keywords: storagegrid, network, networking, ethernet, subnet, routing 
summary: Para configurar las redes de un sistema StorageGRID es necesario contar con un alto nivel de experiencia en conmutación Ethernet, redes TCP/IP, subredes, enrutamiento de red y servidores de seguridad. 
---
= Información general sobre redes de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para configurar las redes de un sistema StorageGRID es necesario contar con un alto nivel de experiencia en conmutación Ethernet, redes TCP/IP, subredes, enrutamiento de red y servidores de seguridad.

Antes de configurar las redes, familiarícese con la arquitectura StorageGRID como se describe en _Grid primer_.

Antes de poner en marcha y configurar StorageGRID, debe configurar la infraestructura de red. La comunicación debe producirse entre todos los nodos de la cuadrícula y entre la cuadrícula y los clientes y servicios externos.

Los clientes externos y los servicios externos necesitan conectarse a redes StorageGRID para realizar funciones como las siguientes:

* Almacenar y recuperar datos de objetos
* Recibir notificaciones por correo electrónico
* Acceder a la interfaz de gestión de StorageGRID (el administrador de grid y el administrador de inquilinos)
* Acceder al recurso compartido de auditoría (opcional)
* Proporcionar servicios como:
+
** Protocolo de hora de red (NTP)
** Sistema de nombres de dominio (DNS)
** Servidor de gestión de claves (KMS)




Las redes de StorageGRID deben configurarse de manera adecuada para manejar el tráfico de estas funciones y más.

Una vez que determine cuál de las tres redes StorageGRID desea usar y cómo se configurarán esas redes, puede instalar y configurar los nodos StorageGRID siguiendo las instrucciones correspondientes.

.Información relacionada
link:../primer/index.html["Imprimador de rejilla"]

link:../admin/index.html["Administre StorageGRID"]

link:../release-notes/index.html["Notas de la versión"]

link:../rhel/index.html["Instale Red Hat Enterprise Linux o CentOS"]

link:../ubuntu/index.html["Instalar Ubuntu o Debian"]

link:../vmware/index.html["Instale VMware"]

link:../sg100-1000/index.html["SG100  servicios de aplicaciones SG1000"]

link:../sg6000/index.html["Dispositivos de almacenamiento SG6000"]

link:../sg5700/index.html["Dispositivos de almacenamiento SG5700"]

link:../sg5600/index.html["Dispositivos de almacenamiento SG5600"]
