---
permalink: sg5600/configuring-storagegrid-connections.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up 
summary: 'Para poder implementar un dispositivo StorageGRID como nodo de almacenamiento en un grid StorageGRID, debe configurar las conexiones entre el dispositivo y las redes que tiene pensado utilizar. Puede configurar las redes examinando el instalador de dispositivos StorageGRID, que está incluido en la controladora E5600SG \(la controladora de computación del dispositivo\).' 
---
= Configurar las conexiones StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para poder implementar un dispositivo StorageGRID como nodo de almacenamiento en un grid StorageGRID, debe configurar las conexiones entre el dispositivo y las redes que tiene pensado utilizar. Puede configurar las redes visitando el instalador de dispositivos de StorageGRID, incluido en la controladora E5600SG (la controladora de computación del dispositivo).

.Pasos
* link:accessing-storagegrid-appliance-installer-sg5600.html["Acceso al instalador de dispositivos de StorageGRID"]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html["Comprobación y actualización de la versión de StorageGRID Appliance Installer"]
* link:configuring-network-links-sg5600.html["Configurar enlaces de red (SG5600)"]
* link:setting-ip-configuration-sg5600.html["Ajuste de la configuración de IP"]
* link:verifying-network-connections.html["Verificación de las conexiones de red"]
* link:verifying-port-level-network-connections.html["Verificación de las conexiones de red a nivel de puerto"]

