---
permalink: sg5600/configuring-hardware.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: Después de aplicar la alimentación al dispositivo, debe configurar Storage Manager de SANtricity, que es el software que utilizará para supervisar el hardware. También debe configurar las conexiones de red que utilizará StorageGRID. 
---
= Configurar el hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de aplicar la alimentación al dispositivo, debe configurar Storage Manager de SANtricity, que es el software que utilizará para supervisar el hardware. También debe configurar las conexiones de red que utilizará StorageGRID.

.Pasos
* link:configuring-storagegrid-connections.html["Configurar las conexiones StorageGRID"]
* link:configuring-santricity-storage-manager.html["Configurando SANtricity Storage Manager"]
* link:optional-enabling-node-encryption.html["Opcional: Habilitar el cifrado de nodos"]
* link:optional-changing-to-raid6-mode-sg5660-only.html["Opcional: Cambiar al modo RAID6 (sólo SG5660)"]
* link:optional-remapping-network-ports-for-appliance-sg5600-and-sg5700.html["Opcional: Reasignación de puertos de red para el dispositivo"]

