---
permalink: sg5600/preparing-for-installation.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, install, installation, preparation, get ready, prepare 
summary: Para preparar la instalación de un dispositivo StorageGRID es necesario preparar el sitio y obtener todo el hardware, cables y herramientas necesarios. También debe recopilar información sobre las direcciones IP y la red. 
---
= Preparación de la instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para preparar la instalación de un dispositivo StorageGRID es necesario preparar el sitio y obtener todo el hardware, cables y herramientas necesarios. También debe recopilar información sobre las direcciones IP y la red.

.Pasos
* link:preparing-site-sg5600.html["Preparación del sitio (SG5600)"]
* link:unpacking-boxes-sg5600.html["Desembalaje de las cajas (SG5600)"]
* link:obtaining-additional-equipment-and-tools-sg5600.html["Obtención de equipos y herramientas adicionales (SG5600)"]
* link:service-laptop-requirements-sg5600.html["Requisitos de mantenimiento de los portátiles"]
* link:web-browser-requirements.html["Requisitos del navegador web"]
* link:reviewing-appliance-network-connections-sg5600.html["Revisar las conexiones de red del dispositivo"]
* link:gathering-installation-information-sg5600.html["Recopilar información de instalación (SG5600)"]

