---
permalink: sg5600/setting-up-santricity-storage-manager.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, SANtricity Storage Manager, SANtricity, Storage Manager, configure, configuring, setup, set up, setting up 
summary: Después de acceder a Storage Manager de SANtricity, puede utilizarlo para configurar los ajustes de hardware. Normalmente, esta configuración se debe configurar antes de poner en marcha el dispositivo como nodo de almacenamiento en un sistema StorageGRID. 
---
= Configure el Administrador de almacenamiento de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de acceder a Storage Manager de SANtricity, puede utilizarlo para configurar los ajustes de hardware. Normalmente, esta configuración se debe configurar antes de poner en marcha el dispositivo como nodo de almacenamiento en un sistema StorageGRID.

.Pasos
* link:configuring-autosupport.html["Configurando AutoSupport"]
* link:verifying-receipt-of-autosupport.html["Verificación de la recepción de AutoSupport"]
* link:configuring-email-and-snmp-trap-alert-notifications.html["Configuración de las notificaciones de alertas de capturas de SNMP y por correo electrónico"]
* link:setting-passwords-for-santricity-storage-manager.html["Configurar contraseñas para SANtricity Storage Manager"]

