---
permalink: sg5600/unable-to-connect-to-storagegrid-appliance-over-network.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, troubleshoot, troubleshooting, connect, connection, unable to connect, no connection 
summary: Si no puede conectarse al dispositivo, puede haber un problema de red o es posible que la instalación del hardware no se haya completado correctamente. 
---
= No se puede conectar con el dispositivo StorageGRID a través de la red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si no puede conectarse al dispositivo, puede haber un problema de red o es posible que la instalación del hardware no se haya completado correctamente.

* *Edición*
+
No puede conectar al aparato.

* *Causa*
+
Esto podría ocurrir si hay un problema de red o la instalación del hardware no se completó correctamente.

* *Acción Correctiva*
+
.. Ping en el aparato: +
`*ping _E5600_controller_IP_*`
.. Abra un explorador e introduzca lo siguiente para acceder al instalador de dispositivos de StorageGRID: +
`*https://_Management_Port_IP_:8443*`
+
Para Management_Port_IP, introduzca la dirección IP para el puerto de gestión 1 en la controladora E5600SG (aprovisionada durante la instalación física).

.. Haga clic en *Configurar red de administración* y compruebe la dirección IP.
.. Si recibe una respuesta del ping, compruebe que el puerto 8443 está abierto en los firewalls.
.. Reinicie el dispositivo.
.. Actualice la página web de instalación.
.. Si esto no resuelve el problema de conexión, póngase en contacto con el soporte técnico del sitio de soporte de NetApp en http://mysupport.netapp.com/["mysupport.netapp.com"^].




.Información relacionada
link:e5600sg-controller-seven-segment-display-codes.html["códigos de visualización de siete segmentos de la controladora E5600SG"]
