---
permalink: vmware/configuration-file-settings.html 
sidebar: sidebar 
keywords:  
summary: El archivo de configuración deploy-vsphere-ovftool.ini contiene las opciones necesarias para poner en marcha nodos de grid virtual. 
---
= Ajustes del archivo de configuración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `deploy-vsphere-ovftool.ini` el archivo de configuración contiene la configuración necesaria para poner en marcha los nodos de grid virtual.

En primer lugar, el archivo de configuración enumera los parámetros globales y, a continuación, enumera los parámetros específicos del nodo en las secciones definidas por el nombre del nodo. Cuando se utilice el archivo:

* _Parámetros globales_ se aplican a todos los nodos de cuadrícula.
* _Parámetros específicos del nodo_ anulan los parámetros globales.




== Parámetros globales

Los parámetros globales se aplican a todos los nodos de cuadrícula, a menos que se anulen por la configuración de secciones individuales. Coloque los parámetros que se aplican a varios nodos en la sección global Parameter y, a continuación, anule estos ajustes según sea necesario en las secciones de nodos individuales.

* *OVFTOOL_ARGUMENTS*: Puede especificar OVFTOOL_ARGUMENTS como configuración global o puede aplicar argumentos individualmente a nodos específicos. Por ejemplo:
+
[source, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=thin --datastore='_datastore_name_'
----
+
Puede utilizar el `--powerOffTarget` y.. `--overwrite` opciones para apagar y sustituir las máquinas virtuales existentes.

+

IMPORTANT: Debe implementar nodos en almacenes de datos diferentes y especificar OVFTOOL_ARGUMENTS para cada nodo, en lugar de globalmente.

* *FUENTE*: La ruta a la plantilla de máquina virtual StorageGRID (`.vmdk`) y el `.ovf` y.. `.mf` archivos para nodos de grid individuales. De forma predeterminada, se utiliza el directorio actual.
+
[source, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* *TARGET*: La URL de la infraestructura virtual (vi) de VMware vSphere para la ubicación en la que se va a implementar StorageGRID. Por ejemplo:
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* *GRID_NETWORK_CONFIG*: Método utilizado para adquirir direcciones IP, TANTO ESTÁTICAS como DHCP. El valor predeterminado es STATIC. Si todos o la mayoría de los nodos utilizan el mismo método para adquirir direcciones IP, puede especificar ese método aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
GRID_NETWORK_CONFIG = DHCP
----
* *GRID_NETWORK_TARGET*: El nombre de una red VMware existente que se utilizará para la red Grid. Si todos los nodos utilizan el mismo nombre de red, o la mayoría de ellos, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
GRID_NETWORK_TARGET = SG-Admin-Network
----
* *GRID_NETWORK_MASK*: La máscara de red para la red Grid. Si todos los nodos o la mayoría de ellos utilizan la misma máscara de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* *GRID_NETWORK_GATEWAY*: El gateway de red para la red Grid. Si todos o la mayoría de los nodos utilizan la misma puerta de enlace de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* * GRID_NETWORK_MTU*: OPCIONAL. La unidad de transmisión máxima (MTU) en la red de red. Si se especifica, el valor debe estar entre 1280 y 9216. Por ejemplo:
+
[listing]
----
GRID_NETWORK_MTU = 8192
----
+
Si se omite, se usa 1400.

+
Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado.

+

IMPORTANT: El valor de MTU de la red debe coincidir con el valor configurado en el puerto del switch al que está conectado el nodo. De lo contrario, pueden ocurrir problemas de rendimiento de red o pérdida de paquetes.

+

IMPORTANT: Para obtener el mejor rendimiento de red, todos los nodos deben configurarse con valores MTU similares en sus interfaces de Grid Network. La alerta *Red de cuadrícula MTU* se activa si hay una diferencia significativa en la configuración de MTU para la Red de cuadrícula en nodos individuales. Los valores de MTU no tienen que ser iguales para todos los tipos de red.

* *ADMIN_NETWORK_CONFIG*: El método utilizado para adquirir direcciones IP, YA SEA DESACTIVADAS, ESTÁTICAS o DHCP. El valor predeterminado es DISABLED. Si todos o la mayoría de los nodos utilizan el mismo método para adquirir direcciones IP, puede especificar ese método aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* *ADMIN_NETWORK_TARGET*: El nombre de una red VMware existente que se utilizará para la red de administración. Esta configuración es necesaria a menos que la red de administración esté deshabilitada. Si todos los nodos utilizan el mismo nombre de red, o la mayoría de ellos, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_TARGET = SG-Admin-Network
----
* *ADMIN_NETWORK_MASK*: La máscara DE red para la red de administración. Este ajuste es obligatorio si se utiliza una dirección IP estática. Si todos los nodos o la mayoría de ellos utilizan la misma máscara de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* *ADMIN_NETWORK_GATEWAY*: La puerta de enlace DE red para la red de administración. Esta configuración es necesaria si está utilizando direcciones IP estáticas y especifica subredes externas en la configuración ADMIN_NETWORK_ESL. (Es decir, no es necesario si ADMIN_NETWORK_ESL está vacío.) Si todos o la mayoría de los nodos utilizan la misma puerta de enlace de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* *ADMIN_NETWORK_ESL*: La lista de subredes externas (rutas) para la Red Admin, especificada como una lista separada por comas de destinos de rutas CIDR. Si todos o la mayoría de los nodos utilizan la misma lista de subredes externas, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* *ADMIN_NETWORK_MTU*: OPCIONAL. La unidad de transmisión máxima (MTU) en la red de administración. No especifique si ADMIN_NETWORK_CONFIG = DHCP. Si se especifica, el valor debe estar entre 1280 y 9216. Si se omite, se usa 1400. Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado. Si todos los nodos, o la mayoría, utilizan el mismo MTU para la red administrativa, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* *CLIENT_NETWORK_CONFIG*: Método utilizado para adquirir direcciones IP, YA SEA DESACTIVADAS, ESTÁTICAS o DHCP. El valor predeterminado es DISABLED. Si todos o la mayoría de los nodos utilizan el mismo método para adquirir direcciones IP, puede especificar ese método aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* *CLIENT_NETWORK_TARGET*: El nombre de una red VMware existente que se utilizará para la red cliente. Esta configuración es necesaria a menos que la red de cliente esté deshabilitada. Si todos los nodos utilizan el mismo nombre de red, o la mayoría de ellos, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_TARGET = SG-Client-Network
----
* *CLIENT_NETWORK_MASK*: La máscara de red para la red cliente. Este ajuste es obligatorio si se utiliza una dirección IP estática. Si todos los nodos o la mayoría de ellos utilizan la misma máscara de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* *CLIENT_NETWORK_GATEWAY*: La puerta de enlace de red para la red cliente. Este ajuste es obligatorio si se utiliza una dirección IP estática. Si todos o la mayoría de los nodos utilizan la misma puerta de enlace de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* *MTU_CLIENTE*: OPCIONAL. La unidad de transmisión máxima (MTU) en la red de cliente. No especifique si CLIENT_NETWORK_CONFIG = DHCP. Si se especifica, el valor debe estar entre 1280 y 9216. Si se omite, se usa 1400. Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado. Si todos o la mayoría de los nodos utilizan el mismo MTU para la red de cliente, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* *PORT_REMAPP*: Reasigna cualquier puerto utilizado por un nodo para comunicaciones internas de nodo de red o comunicaciones externas. Es necesario volver a asignar puertos si las políticas de red de la empresa restringen uno o varios puertos utilizados por StorageGRID. Para obtener una lista de puertos que utiliza StorageGRID, consulte Comunicaciones internas de los nodos de grid y comunicaciones externas en link:../network/index.html["Directrices sobre redes"].
+

IMPORTANT: No reasigne los puertos que está planeando utilizar para configurar los puntos finales del equilibrador de carga.

+

NOTE: Si sólo SE establece PORT_REMAPP, la asignación que especifique se utilizará para las comunicaciones entrantes y salientes. Si TAMBIÉN se especifica PORT_REMAPP_INBOUND, PORT_REMAPP sólo se aplica a las comunicaciones salientes.



El formato utilizado es: `_network type_/_protocol/_default port used by grid node_/_new port_`, donde tipo de red es grid, administrador o cliente y protocolo es tcp o udp.

Por ejemplo:

[listing]
----
PORT_REMAP = client/tcp/18082/443
----
Si se utiliza solo, este ejemplo establece una asignación simétrica de las comunicaciones entrantes y salientes del nodo de cuadrícula desde el puerto 18082 al puerto 443. Si se utiliza junto con PORT_REMAPP_INBOUND, este ejemplo asigna las comunicaciones salientes del puerto 18082 al puerto 443.

* *PORT_REMAPP_INBOUND*: Reasigna las comunicaciones entrantes para el puerto especificado. Si especifica PORT_REMAPP_INBOUND pero no especifica un valor para PORT_REMAPP, las comunicaciones salientes para el puerto no se modifican.
+

IMPORTANT: No reasigne los puertos que está planeando utilizar para configurar los puntos finales del equilibrador de carga.



El formato utilizado es: `_network type_/_protocol/_default port used by grid node_/_new port_`, donde tipo de red es grid, administrador o cliente y protocolo es tcp o udp.

Por ejemplo:

[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
En este ejemplo se toma el tráfico que se envía al puerto 443 para pasar un firewall interno y lo dirige al puerto 18082, donde el nodo de grid está escuchando las solicitudes de S3.



== Parámetros específicos del nodo

Cada nodo se encuentra en su propia sección del archivo de configuración. Cada nodo requiere la siguiente configuración:

* El encabezado de sección define el nombre del nodo que se mostrará en el Gestor de cuadrícula. Puede anular este valor especificando el parámetro opcional NODE_NAME para el nodo.
* *NODE_TYPE*: VM_Admin_Node, VM_Storage_Node, VM_Archive_Node o VM_API_Gateway_Node
* *GRID_NETWORK_IP*: La dirección IP del nodo en la red de cuadrícula.
* *ADMIN_NETWORK_IP*: La dirección IP del nodo en la red de administración. Solo es obligatorio si el nodo está conectado a la red Admin y ADMIN_NETWORK_CONFIG se establece en STATIC.
* *IP_RED_CLIENTE*: La dirección IP del nodo en la red cliente. Es obligatorio sólo si el nodo está conectado a la red cliente y CLIENT_NETWORK_CONFIG para este nodo se establece en ESTÁTICO.
* *ADMIN_IP*: La dirección IP del nodo Admin primario de la red Grid. Utilice el valor especificado como GRID_NETWORK_IP para el nodo de administración principal. Si omite este parámetro, el nodo intenta detectar la IP del nodo de administración principal mediante mDNS. Para obtener más información, consulte link:how-grid-nodes-discover-primary-admin-node.html["La forma en que los nodos de grid detectan el nodo de administrador principal"].
+

NOTE: El parámetro ADMIN_IP se omite para el nodo de administración principal.

* Todos los parámetros que no se establecieron globalmente. Por ejemplo, si un nodo está conectado a la red de administrador y no especificó parámetros DE RED_ADMIN en todo el mundo, debe especificarlos para el nodo.




== Nodo de administrador principal

Se necesitan las siguientes configuraciones adicionales para el nodo de administración principal:

* *NODE_TYPE*: VM_Admin_Node
* *ROL_ADMINISTRADOR*: Primario


Esta entrada de ejemplo es para un nodo de administrador principal que está en las tres redes:

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
La siguiente configuración adicional es opcional para el nodo de administración principal:

* *DISCO*: De forma predeterminada, a los nodos de administración se les asignan dos discos duros adicionales de 200 GB para la auditoría y el uso de bases de datos. Es posible aumentar esta configuración con el parámetro DISK. Por ejemplo:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: Para los nodos de administrador, LAS INSTANCIAS siempre deben ser iguales 2.



== Nodo de almacenamiento

Se requiere la siguiente configuración adicional para los nodos de almacenamiento:

* *NODE_TYPE*: VM_Storage_Node
+
Esta entrada de ejemplo es para un nodo de almacenamiento que se encuentra en las redes Grid y Admin, pero no en la red cliente. Este nodo utiliza LA configuración ADMIN_IP para especificar la dirección IP del nodo de administración principal en la red de grid.

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
Esta segunda entrada de ejemplo es para un nodo de almacenamiento en una red cliente donde la política de red empresarial del cliente establece que una aplicación cliente S3 sólo puede acceder al nodo de almacenamiento mediante el puerto 80 o 443. El archivo de configuración de ejemplo utiliza PORT_REMAP para habilitar el nodo de almacenamiento para enviar y recibir mensajes S3 en el puerto 443.

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
El último ejemplo crea una reasignación simétrica para el tráfico ssh del puerto 22 al puerto 3022, pero establece explícitamente los valores para el tráfico entrante y saliente.

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


La siguiente configuración adicional es opcional para nodos de almacenamiento:

* *DISCO*: De forma predeterminada, a los nodos de almacenamiento se les asignan tres discos de 4 TB para el uso de RangeDB. Esta configuración se puede aumentar con el parámetro DISK. Por ejemplo:
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----




== Nodo de archivado

Se requiere la siguiente configuración adicional para los nodos de archivado:

* *NODE_TYPE*: VM_Archive_Node


Esta entrada de ejemplo es para un nodo de archivado que se encuentra en las redes Grid y Admin, pero no en la red cliente.

[listing]
----
[DC1-ARC1]
  NODE_TYPE = VM_Archive_Node

  GRID_NETWORK_IP = 10.1.0.4
  ADMIN_NETWORK_IP = 10.3.0.4

  ADMIN_IP = 10.1.0.2
----


== Nodo de puerta de enlace

Para los nodos de puerta de enlace se requiere la siguiente configuración adicional:

* *NODE_TYPE*: VM_API_GATEWAY


Esta entrada de ejemplo es para un nodo de puerta de enlace de ejemplo en las tres redes. En este ejemplo, no se especificó ningún parámetro de red de cliente en la sección global del archivo de configuración, por lo que se deben especificar para el nodo:

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG-Client-Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----


== Nodo de administrador no primario

Se requieren los siguientes ajustes adicionales para los nodos del administrador que no son primarios:

* *NODE_TYPE*: VM_Admin_Node
* *ROL_ADMIN*: No primario


Esta entrada de ejemplo es para un nodo de administración no primario que no está en la red de cliente:

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG-Grid-Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
La siguiente configuración adicional es opcional para los nodos de administrador que no son primarios:

* *DISCO*: De forma predeterminada, a los nodos de administración se les asignan dos discos duros adicionales de 200 GB para la auditoría y el uso de bases de datos. Es posible aumentar esta configuración con el parámetro DISK. Por ejemplo:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: Para los nodos de administrador, LAS INSTANCIAS siempre deben ser iguales 2.

.Información relacionada
link:how-grid-nodes-discover-primary-admin-node.html["La forma en que los nodos de grid detectan el nodo de administrador principal"]

link:../network/index.html["Directrices sobre redes"]
