---
permalink: rhel/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, redhat, rhel, download installation files, downloading installation files 
summary: Debe descargar el archivo de instalación de StorageGRID y extraer los archivos necesarios. 
---
= Descarga y extracción de los archivos de instalación de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe descargar el archivo de instalación de StorageGRID y extraer los archivos necesarios.

.Pasos
. Vaya a la página de descargas de NetApp para StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Descargas de NetApp: StorageGRID"^]

. Seleccione el botón para descargar la última versión, o seleccione otra versión en el menú desplegable y seleccione *Ir*.
. Inicie sesión con el nombre de usuario y la contraseña de su cuenta de NetApp.
. Si aparece una instrucción Caution/MustRead, léala y active la casilla de verificación.
+
Debe aplicar cualquier revisión requerida después de instalar la versión de StorageGRID. Para obtener más información, vea el procedimiento de revisión en las instrucciones de recuperación y mantenimiento.

. Lea el contrato de licencia para usuario final, seleccione la casilla de verificación y, a continuación, seleccione *Aceptar y continuar*.
. En la columna *instalar StorageGRID*, seleccione el software apropiado.
+
Descargue el `.tgz` o. `.zip` archivado de archivos para su plataforma.

+
Los archivos comprimidos contienen los archivos RPM y secuencias de comandos para Red Hat Enterprise Linux o CentOS.

+

NOTE: Utilice la `.zip` Archivo si está ejecutando Windows en el portátil de servicio.

. Guarde y extraiga el archivo de archivado.
. Elija los archivos que necesite en la siguiente lista.
+
Los archivos que necesite dependen de la topología de cuadrícula planificada y de cómo implementar el sistema StorageGRID.

+

NOTE: Las rutas enumeradas en la tabla son relativas al directorio de nivel superior instalado por el archivo de instalación extraído.



[cols="1a,2a"]
|===
| Ruta y nombre de archivo | Descripción 


| ./rpms/README  a| 
Archivo de texto que describe todos los archivos contenidos en el archivo de descarga de StorageGRID.



| ./rpms/NLF000000.txt  a| 
Una licencia gratuita que no proporciona ningún derecho de soporte para el producto.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
PAQUETE RPM para instalar las imágenes de nodo StorageGRID en sus hosts RHEL o CentOS.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
PAQUETE RPM para instalar el servicio host StorageGRID en sus hosts RHEL o CentOS.



| Herramienta de secuencia de comandos de la implementación | Descripción 


| ./rpms/configure-storagegrid.py  a| 
Script Python que se utiliza para automatizar la configuración de un sistema StorageGRID.



| ./rpms/configure-sga.py  a| 
Una secuencia de comandos Python que se utiliza para automatizar la configuración de los dispositivos StorageGRID.



| ./rpms/configure-storagegrid.sample.json  a| 
Un archivo de configuración de ejemplo que se puede utilizar con `configure-storagegrid.py` guión.



| ./rpms/storagegrid-ssoauth.py  a| 
Ejemplo de secuencia de comandos Python que puede utilizar para iniciar sesión en la API de gestión de grid cuando está activado el inicio de sesión único.



| ./rpms/configure-storagegrid.blank.json  a| 
Un archivo de configuración en blanco para usar con el `configure-storagegrid.py` guión.



| ./rpms/extras/ansible  a| 
Ejemplo de rol de Ansible y libro de estrategia para configurar hosts de RHEL o CentOS para puesta en marcha del contenedor StorageGRID. Puede personalizar el rol o el libro de estrategia según sea necesario.

|===
.Información relacionada
link:../maintain/index.html["Mantener  recuperar"]
