---
permalink: rhel/required-materials.html 
sidebar: sidebar 
keywords: storagegrid, redhat required materials, rhel required materials, redhat installation, rhel installation, storagegrid license 
summary: Antes de instalar StorageGRID, debe recopilar y preparar los materiales necesarios. 
---
= Materiales requeridos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar StorageGRID, debe recopilar y preparar los materiales necesarios.

[cols="1a,2a"]
|===
| Elemento | Notas 


 a| 
Licencia de StorageGRID de NetApp
 a| 
Debe tener una licencia de NetApp válida y con firma digital.

*Nota*: En el archivo de instalación de StorageGRID se incluye una licencia de no producción, que puede utilizarse para probar y probar cuadrículas de concepto.



 a| 
Archivo de instalación de StorageGRID
 a| 
Debe descargar el archivo de instalación de StorageGRID y extraer los archivos.



 a| 
Portátil de servicio
 a| 
El sistema StorageGRID se instala a través de un ordenador portátil de servicio.

El portátil de servicio debe tener:

* Puerto de red
* Cliente SSH (por ejemplo, PuTTY)
* Navegador web compatible




 a| 
Documentación de StorageGRID
 a| 
* Notas de la versión
* Instrucciones para administrar StorageGRID


|===
.Información relacionada
link:downloading-and-extracting-storagegrid-installation-files.html["Descarga y extracción de los archivos de instalación de StorageGRID"]

link:web-browser-requirements.html["Requisitos del navegador web"]

link:../admin/index.html["Administre StorageGRID"]

link:../release-notes/index.html["Notas de la versión"]
