---
permalink: admin/completing-archive-node-setup.html 
sidebar: sidebar 
keywords:  
summary: El nodo de archivado no funciona después de completar el proceso de instalación. Antes de que el sistema StorageGRID pueda guardar objetos en el nodo de archivado de TSM, debe completar la instalación y configuración del servidor TSM y configurar el nodo de archivado para que se comunique con el servidor TSM. 
---
= Completar la configuración del nodo de archivado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El nodo de archivado no funciona después de completar el proceso de instalación. Antes de que el sistema StorageGRID pueda guardar objetos en el nodo de archivado de TSM, debe completar la instalación y configuración del servidor TSM y configurar el nodo de archivado para que se comunique con el servidor TSM.

Para obtener más información sobre cómo optimizar la recuperación de TSM y las sesiones de almacenamiento, consulte la información sobre cómo gestionar el almacenamiento de archivos.

* link:managing-archive-nodes.html["Gestión de los nodos de archivado"]


Consulte la siguiente documentación de IBM, según sea necesario, cuando prepare el servidor TSM para la integración con el nodo de archivado en un sistema StorageGRID:

* http://www.ibm.com/support/docview.wss?rs=577&uid=ssg1S7002972["Guía del usuario e instalación de los controladores de dispositivos de cinta de IBM"^]
* http://www.ibm.com/support/docview.wss?rs=577&uid=ssg1S7003032["Referencia de programación de controladores de dispositivo de cinta IBM"^]

