---
permalink: admin/configuring-sso.html 
sidebar: sidebar 
keywords:  
summary: 'Cuando se habilita el inicio de sesión único \(SSO\), los usuarios solo pueden acceder a Grid Manager, al arrendatario Manager, a la API de gestión de grid o a la API de gestión de inquilinos si sus credenciales están autorizadas mediante el proceso de inicio de sesión SSO implementado por la organización.' 
---
= Configuración del inicio de sesión único
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se habilita el inicio de sesión único (SSO), los usuarios solo pueden acceder a Grid Manager, al arrendatario Manager, a la API de gestión de grid o a la API de gestión de inquilinos si sus credenciales están autorizadas mediante el proceso de inicio de sesión SSO implementado por la organización.

* link:confirming-federated-users-can-sign-in.html["Confirmación de que los usuarios federados pueden iniciar sesión"]
* link:using-sandbox-mode.html["Uso del modo de recinto de seguridad"]
* link:creating-relying-party-trusts-in-ad-fs.html["Creación de confianzas de parte de confianza en AD FS"]
* link:testing-relying-party-trusts.html["Prueba de fideicomisos de la parte de confianza"]
* link:enabling-single-sign-on.html["Habilitar el inicio de sesión único"]
* link:disabling-single-sign-on.html["Desactivar el inicio de sesión único"]
* link:temporarily-disabling-and-reenabling-sso-for-admin-node.html["Desactive y vuelva a habilitar temporalmente el inicio de sesión único para un nodo de administración"]

