---
permalink: admin/controlling-access-through-firewalls.html 
sidebar: sidebar 
keywords:  
summary: Cuando desee controlar el acceso a través de firewalls, puede abrir o cerrar puertos específicos en el firewall externo. 
---
= Controlar el acceso mediante firewalls
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando desee controlar el acceso a través de firewalls, puede abrir o cerrar puertos específicos en el firewall externo.



== Control del acceso en el firewall externo

Puede controlar el acceso a las interfaces de usuario y las API de los nodos de administrador de StorageGRID. Para ello, abra y cierre puertos específicos en el firewall externo. Por ejemplo, es posible que desee evitar que los inquilinos puedan conectarse a Grid Manager en el firewall, además de utilizar otros métodos para controlar el acceso al sistema.

[cols="1a,1a,2a"]
|===
| Puerto | Descripción | Si el puerto está abierto... 


 a| 
443
 a| 
Puerto HTTPS predeterminado para nodos de administración
 a| 
Los exploradores web y los clientes de la API de gestión pueden acceder a Grid Manager, a la API de gestión de grid, al administrador de inquilinos y a la API de gestión de inquilinos.

*Nota:* el puerto 443 también se utiliza para tráfico interno.



 a| 
8443
 a| 
Puerto de Grid Manager restringido en nodos de administración
 a| 
* Los exploradores web y los clientes de la API de gestión pueden acceder a Grid Manager y a la API de gestión de grid mediante HTTPS.
* Los exploradores web y los clientes de API de gestión no pueden acceder al administrador de inquilinos ni a la API de gestión de inquilinos.
* Se rechazarán las solicitudes de contenido interno.




 a| 
9443
 a| 
Puerto de administrador de inquilinos restringido en los nodos de administrador
 a| 
* Los exploradores web y los clientes de API de gestión pueden acceder al administrador de inquilinos y a la API de gestión de inquilinos mediante HTTPS.
* Los exploradores web y los clientes de la API de administración no pueden acceder a Grid Manager ni a la API de gestión de grid.
* Se rechazarán las solicitudes de contenido interno.


|===

IMPORTANT: El inicio de sesión único (SSO) no está disponible en los puertos de administrador de grid restringido o de administrador de inquilinos. Debe utilizar el puerto HTTPS predeterminado (443) si desea que los usuarios se autentiquen con inicio de sesión único.

.Información relacionada
link:signing-in-to-grid-manager.html["Iniciando sesión en Grid Manager"]

link:creating-tenant-account-if-storagegrid-is-not-using-sso.html["Creación de una cuenta de inquilino si StorageGRID no utiliza SSO"]

link:summary-ip-addresses-and-ports-for-client-connections.html["Resumen: Direcciones IP y puertos para conexiones cliente"]

link:managing-untrusted-client-networks.html["Administración de redes de clientes que no son de confianza"]

link:../ubuntu/index.html["Instalar Ubuntu o Debian"]

link:../vmware/index.html["Instale VMware"]

link:../rhel/index.html["Instale Red Hat Enterprise Linux o CentOS"]
