---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords:  
summary: StorageGRID admite hasta tres interfaces de red por nodo de grid, lo que permite configurar la red para cada nodo de grid individual de modo que se ajuste a sus requisitos de seguridad y acceso. 
---
= Directrices para redes StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID admite hasta tres interfaces de red por nodo de grid, lo que permite configurar la red para cada nodo de grid individual de modo que se ajuste a sus requisitos de seguridad y acceso.


NOTE: Para modificar o añadir una red para un nodo de grid, consulte las instrucciones de recuperación y mantenimiento. Para obtener más información acerca de la topología de red, consulte las instrucciones de redes.



== Red Grid

Obligatorio. La red de red se utiliza para todo el tráfico interno de StorageGRID. Proporciona conectividad entre todos los nodos de la cuadrícula, en todos los sitios y subredes.



== Red de administración

Opcional. La red de administración suele utilizarse para la administración y el mantenimiento del sistema. También se puede utilizar para el acceso a protocolos de cliente. La red de administración suele ser una red privada y no es necesario que se pueda enrutar entre sitios.



== Red cliente

Opcional. La red cliente es una red abierta que se suele utilizar para proporcionar acceso a aplicaciones cliente S3 y Swift, de modo que la red Grid se pueda aislar y proteger. La red de cliente puede comunicarse con cualquier subred accesible a través de la puerta de enlace local.



== Directrices

* Cada nodo de grid StorageGRID requiere una interfaz de red dedicada, una dirección IP, una máscara de subred y una puerta de enlace para cada red a la que está asignado.
* Un nodo de grid no puede tener más de una interfaz en una red.
* Se admite una sola puerta de enlace, por red y cada nodo de grid, y debe estar en la misma subred que el nodo. Si es necesario, puede implementar un enrutamiento más complejo en la puerta de enlace.
* En cada nodo, cada red asigna una interfaz de red específica.
+
[cols="1a,1a"]
|===
| Red | Nombre de la interfaz 


 a| 
Cuadrícula
 a| 
eth0



 a| 
Admin (opcional)
 a| 
eth1



 a| 
Cliente (opcional)
 a| 
eth2

|===
* Si el nodo está conectado a un dispositivo StorageGRID, se utilizan puertos específicos para cada red. Para obtener más información, consulte las instrucciones de instalación del dispositivo.
* La ruta predeterminada se genera automáticamente, por nodo. Si eth2 está habilitado, 0.0.0.0/0 utiliza la red cliente en eth2. Si eth2 no está habilitado, 0.0.0.0/0 utiliza la red de cuadrícula en eth0.
* La red cliente no se pone en funcionamiento hasta que el nodo de grid se ha Unido a la cuadrícula
* La red de administrador se puede configurar durante la puesta en marcha del nodo de grid para permitir el acceso a la interfaz de usuario de la instalación antes de que la cuadrícula esté totalmente instalada.


.Información relacionada
link:../maintain/index.html["Mantener  recuperar"]

link:../network/index.html["Directrices de red"]
