---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords:  
summary: 'Puede que desee utilizar grupos de alta disponibilidad \(ha\) por varios motivos.' 
---
= Cómo se utilizan los grupos de alta disponibilidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede que quiera utilizar grupos de alta disponibilidad por varios motivos.

* Un grupo de alta disponibilidad puede proporcionar conexiones administrativas de alta disponibilidad al administrador de grid o al administrador de inquilinos.
* Un grupo de alta disponibilidad puede proporcionar conexiones de datos de alta disponibilidad para clientes S3 y Swift.
* Un grupo de alta disponibilidad que contiene una sola interfaz le permite proporcionar muchas direcciones VIP y establecer explícitamente direcciones IPv6.


Un grupo de alta disponibilidad solo puede proporcionar alta disponibilidad si todos los nodos incluidos en el grupo proporcionan los mismos servicios. Cuando crea un grupo de alta disponibilidad, añada interfaces desde los tipos de nodos que proporcionan los servicios necesarios.

* *Admin Nodes*: Incluye el servicio Load Balancer y permite el acceso al Grid Manager o al arrendatario Manager.
* *Nodos de puerta de enlace*: Incluye el servicio Load Balancer y el servicio CLB (obsoleto).


[cols="1a,1a"]
|===
| Objetivo del grupo de alta disponibilidad | Añada nodos de este tipo al grupo de alta disponibilidad 


 a| 
Acceso a Grid Manager
 a| 
* Nodo de administración principal (*Master* preferido)
* Nodos de administrador no primario


*Nota:* el nodo de administración principal debe ser el Master preferido. Algunos procedimientos de mantenimiento solo se pueden realizar desde el nodo de administración principal.



 a| 
Acceso solo al administrador de inquilinos
 a| 
* Nodos de administrador primario o no primario




 a| 
Acceso al cliente de S3 o Swift: Servicio Load Balancer
 a| 
* Nodos de administración
* Nodos de puerta de enlace




 a| 
Acceso al cliente S3 o Swift: Servicio CLB

*Nota:* el servicio CLB está en desuso.
 a| 
* Nodos de puerta de enlace


|===


== Limitaciones en el uso de grupos de alta disponibilidad con Grid Manager o Intenant Manager

El fallo de los servicios del administrador de grid o del administrador de inquilinos no activa la conmutación por error dentro del grupo de alta disponibilidad.

Si ha iniciado sesión en Grid Manager o en el arrendatario Manager cuando se produce la conmutación por error, ha cerrado sesión y debe volver a iniciar sesión para reanudar la tarea.

No se pueden realizar algunos procedimientos de mantenimiento cuando el nodo administrador principal no está disponible. Durante la conmutación por error, puede utilizar Grid Manager para supervisar el sistema StorageGRID.



== Limitaciones del uso de grupos de alta disponibilidad con el servicio CLB

El error del servicio CLB no activa la conmutación por error dentro del grupo ha.


NOTE: El servicio CLB está obsoleto.
