---
permalink: admin/migrating-data-into-storagegrid.html 
sidebar: sidebar 
keywords:  
summary: Puede migrar grandes cantidades de datos al sistema StorageGRID a la vez que utiliza el sistema StorageGRID para realizar operaciones diarias. 
---
= Migración de datos a StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede migrar grandes cantidades de datos al sistema StorageGRID a la vez que utiliza el sistema StorageGRID para realizar operaciones diarias.

La siguiente sección es una guía para comprender y planificar una migración de grandes cantidades de datos al sistema StorageGRID. No es una guía general sobre la migración de datos y no incluye pasos detallados para realizar una migración. Siga las directrices y las instrucciones de esta sección para asegurarse de que la migración de datos al sistema StorageGRID se realice de forma eficiente sin interferir en las operaciones del día a día y de que el sistema StorageGRID gestione los datos migrados de forma adecuada.

* link:confirming-capacity-of-storagegrid-system.html["Confirmación de la capacidad del sistema StorageGRID"]
* link:determining-ilm-policy-for-migrated-data.html["Determinación de la política de ILM para los datos migrados"]
* link:impact-of-migration-on-operations.html["Impacto de la migración en las operaciones"]
* link:scheduling-data-migration.html["Programación de la migración de datos"]
* link:monitoring-data-migration.html["Supervisar la migración de datos"]
* link:creating-custom-notifications-for-migration-alarms.html["Creación de notificaciones personalizadas para las alarmas de migración"]

