---
permalink: admin/setting-archive-node-to-read-only-if-tsm-middleware-reaches-capacity.html 
sidebar: sidebar 
keywords:  
summary: Si el servidor de middleware TSM objetivo alcanza la capacidad, el nodo de archivado se puede optimizar para realizar únicamente recuperaciones. 
---
= Configurar el nodo de archivado como de sólo lectura si el middleware TSM alcanza la capacidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si el servidor de middleware TSM objetivo alcanza la capacidad, el nodo de archivado se puede optimizar para realizar únicamente recuperaciones.

.Lo que necesitará
* Debe iniciar sesión en Grid Manager mediante un explorador compatible.
* Debe tener permisos de acceso específicos.


.Pasos
. Seleccione *Soporte* > *Herramientas* > *Topología de cuadrícula*.
. Seleccione *_Archive Node_* > *ARC* > *Target*.
. Seleccione *Configuración* > *Principal*.
. Cambie el número máximo de sesiones de recuperación para que sea el mismo que el número de sesiones simultáneas enumeradas en el número de sesiones.
. Cambie el número máximo de sesiones de almacenamiento a 0.
+

NOTE: No es necesario cambiar el número máximo de sesiones de almacén a 0 si el nodo de archivado es de sólo lectura. No se crearán sesiones de almacenamiento.

. Haga clic en *aplicar cambios*.

