---
permalink: s3/benefits-of-active-idle-and-concurrent-http-connections.html 
sidebar: sidebar 
keywords:  
summary: La forma en que se configuran las conexiones HTTP puede afectar el rendimiento del sistema StorageGRID. Las configuraciones varían en función de si la conexión HTTP está activa o inactiva o si tiene varias conexiones simultáneas. 
---
= Ventajas de las conexiones HTTP activas, inactivas y simultáneas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La forma en que se configuran las conexiones HTTP puede afectar el rendimiento del sistema StorageGRID. Las configuraciones varían en función de si la conexión HTTP está activa o inactiva o si tiene varias conexiones simultáneas.

Puede identificar las ventajas en el rendimiento de los siguientes tipos de conexiones HTTP:

* Conexiones HTTP inactivas
* Conexiones HTTP activas
* Conexiones HTTP simultáneas


.Información relacionada
* link:benefits-of-keeping-idle-http-connections-open.html["Ventajas de mantener abiertas las conexiones HTTP inactivas"]
* link:benefits-of-active-http-connections.html["Ventajas de las conexiones HTTP activas"]
* link:benefits-of-concurrent-http-connections.html["Ventajas de las conexiones HTTP simultáneas"]
* link:separation-of-http-connection-pools-for-read-and-write-operations.html["Separación de grupos de conexiones HTTP para operaciones de lectura y escritura"]

