---
permalink: s3/storagegrid-s3-rest-api-operations.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Operaciones de la API de REST de StorageGRID S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existen operaciones añadidas en la API DE REST de S3 específicas del sistema StorageGRID.



== OBTENGA la solicitud de consistencia de bloque

La solicitud DE consistencia DE GET Bucket permite determinar el nivel de consistencia que se aplica a un bloque determinado.

Los controles de consistencia predeterminados se establecen para garantizar la lectura tras escritura de los objetos recién creados.

Debe tener el permiso s3:GetBucketConsistency, o bien ser la raíz de la cuenta, para completar esta operación.



=== Ejemplo de solicitud

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== Respuesta

En la respuesta XML, `<Consistency>` devolverá uno de los siguientes valores:

|===
| Control de consistencia | Descripción 


 a| 
todo
 a| 
Todos los nodos reciben los datos inmediatamente o se produce un error en la solicitud.



 a| 
fuerte en todo el mundo
 a| 
Garantiza la coherencia de lectura tras escritura para todas las solicitudes del cliente en todos los sitios.



 a| 
sitio seguro
 a| 
Garantiza la coherencia de lectura tras escritura para todas las solicitudes del cliente dentro de un sitio.



 a| 
lectura-después-nueva-escritura
 a| 
(Predeterminado) proporciona coherencia de lectura tras escritura para los nuevos objetos y coherencia final para las actualizaciones de objetos. Ofrece garantías de alta disponibilidad y protección de datos. Coincide con las garantías de coherencia de Amazon S3.

*Nota:* Si su aplicación utiliza PETICIONES HEAD en objetos que no existen, puede recibir un número elevado de 500 errores de Internal Server si uno o más nodos de almacenamiento no están disponibles. Para evitar estos errores, establezca el control de coherencia en "'Available'" a menos que necesite garantías de coherencia similares a las de Amazon S3.



 a| 
Disponible (coherencia eventual para operaciones DE CABEZAL)
 a| 
Se comporta del mismo modo que el nivel de consistencia "read-after-new-write", pero sólo proporciona consistencia eventual para las operaciones DE CABEZA. Ofrece una mayor disponibilidad para las OPERACIONES DE CABEZAL que una «escritura tras otra» si los nodos de almacenamiento no están disponibles. Se diferencia de las garantías de coherencia de Amazon S3 solo para operaciones HEAD.

|===


=== Ejemplo de respuesta

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
.Información relacionada
link:consistency-controls.html["Controles de consistencia"]



== PONER solicitud de consistencia de bloque

La solicitud PUT Bucket Consistency permite especificar el nivel de coherencia que se va a aplicar a las operaciones realizadas en un bloque.

Los controles de consistencia predeterminados se establecen para garantizar la lectura tras escritura de los objetos recién creados.

Debe tener el permiso s3:PutBucketConsistency, o bien ser la raíz de la cuenta, para completar esta operación.



=== Solicitud

La `x-ntap-sg-consistency` el parámetro debe contener uno de los siguientes valores:

|===
| Control de consistencia | Descripción 


 a| 
todo
 a| 
Todos los nodos reciben los datos inmediatamente o se produce un error en la solicitud.



 a| 
fuerte en todo el mundo
 a| 
Garantiza la coherencia de lectura tras escritura para todas las solicitudes del cliente en todos los sitios.



 a| 
sitio seguro
 a| 
Garantiza la coherencia de lectura tras escritura para todas las solicitudes del cliente dentro de un sitio.



 a| 
lectura-después-nueva-escritura
 a| 
(Predeterminado) proporciona coherencia de lectura tras escritura para los nuevos objetos y coherencia final para las actualizaciones de objetos. Ofrece garantías de alta disponibilidad y protección de datos. Coincide con las garantías de coherencia de Amazon S3.

*Nota:* Si su aplicación utiliza PETICIONES HEAD en objetos que no existen, puede recibir un número elevado de 500 errores de Internal Server si uno o más nodos de almacenamiento no están disponibles. Para evitar estos errores, establezca el control de coherencia en "'Available'" a menos que necesite garantías de coherencia similares a las de Amazon S3.



 a| 
Disponible (coherencia eventual para operaciones DE CABEZAL)
 a| 
Se comporta del mismo modo que el nivel de consistencia "read-after-new-write", pero sólo proporciona consistencia eventual para las operaciones DE CABEZA. Ofrece una mayor disponibilidad para las OPERACIONES DE CABEZAL que una «escritura tras otra» si los nodos de almacenamiento no están disponibles. Se diferencia de las garantías de coherencia de Amazon S3 solo para operaciones HEAD.

|===
*Nota:* en general, se debe utilizar el valor de control de la coherencia "read-after-new-write". Si las solicitudes no funcionan correctamente, cambie el comportamiento del cliente de la aplicación, si es posible. O bien, configure el cliente para especificar el control de consistencia de cada solicitud API. Establecer el control de consistencia a nivel de cucharón únicamente como último recurso.



=== Ejemplo de solicitud

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-consistency=strong-global HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.Información relacionada
link:consistency-controls.html["Controles de consistencia"]



== GET Bucket última solicitud de tiempo de acceso

La solicitud DE tiempo DE acceso del último bloque DE GET Bucket permite determinar si las actualizaciones de la última hora de acceso están habilitadas o deshabilitadas para bloques individuales.

Para completar esta operación, debe tener el permiso s3:GetBucketLastAccessTime, o ser la raíz de la cuenta.



=== Ejemplo de solicitud

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-lastaccesstime HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== Ejemplo de respuesta

Este ejemplo muestra que las actualizaciones de la última hora de acceso están habilitadas para el bloque.

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/10.3.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<LastAccessTime xmlns="http://s3.storagegrid.com/doc/2015-02-01/">enabled
</LastAccessTime>
----


== PUT Bucket última solicitud de tiempo de acceso

La solicitud DE la última hora de acceso al bloque DE PUT permite habilitar o deshabilitar las actualizaciones del último tiempo de acceso para bloques individuales. Al deshabilitar las actualizaciones de la última hora de acceso, se mejora el rendimiento, y es la configuración predeterminada para todos los bloques creados con la versión 10.3.0 o posterior.

Para completar esta operación, debe tener el permiso s3:PutBucketLastAccessTime para un bloque o ser raíz de cuenta.


NOTE: A partir de la versión 10.3 de StorageGRID, las actualizaciones de la última hora de acceso se deshabilitan de forma predeterminada para todos los bloques nuevos. Si tiene bloques que se crearon con una versión anterior de StorageGRID y desea coincidir con el nuevo comportamiento predeterminado, debe deshabilitar explícitamente las actualizaciones de la última hora de acceso para cada uno de esos bloques anteriores. Puede habilitar o deshabilitar las actualizaciones para la última hora de acceso mediante LA solicitud DE LA última hora de ACCESO DE PUT Bucket, la casilla de verificación *S3* > *Cuchos* > *Cambiar la última configuración de acceso* en el Administrador de inquilinos o la API de administración de inquilinos.

Si se desactivan las actualizaciones de la última hora de acceso para un bloque, se aplicará el siguiente comportamiento a las operaciones del bloque:

* LAS solicitudes GET Object, GET Object ACL, GET Object Etiquetado y HEAD Object no actualizan la última hora de acceso. El objeto no se agrega a las colas para la evaluación de la gestión del ciclo de vida de la información (ILM).
* PUT Object (PONER objeto): Copie y COLOQUE las solicitudes de etiquetado de objetos que sólo actualizan los metadatos. También actualice la hora del último acceso. El objeto se agrega a las colas para la evaluación de ILM.
* Si las actualizaciones a la hora del último acceso están deshabilitadas para el bloque de origen, PUT Object - Copy Requests no actualizan la hora del último acceso para el bloque de origen. El objeto que se copió no se agrega a colas para la evaluación de ILM para el bloque de origen. Sin embargo, PARA el destino, PONER objeto - Copiar solicitudes siempre actualizar la última hora de acceso. La copia del objeto se agrega a las colas para la evaluación de ILM.
* Completar solicitudes de carga de varias partes actualizar la última hora de acceso. El objeto completado se agrega a las colas para la evaluación de ILM.




=== Solicitar ejemplos

En este ejemplo se habilita la hora de último acceso para un bloque.

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-lastaccesstime=enabled HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
En este ejemplo se deshabilita la hora de último acceso para un bloque.

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-lastaccesstime=disabled HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.Información relacionada
link:../tenant/index.html["Usar una cuenta de inquilino"]



== DELETE bucket metadata notification Configuration

La solicitud de configuración DE notificación DE metadatos DELETE Bucket permite deshabilitar el servicio de integración de búsqueda para bloques individuales al eliminar el XML de configuración.

Para completar esta operación, debe tener el permiso s3:DeleteBucketMetadataNotification para un bloque o ser raíz de cuenta.



=== Ejemplo de solicitud

Este ejemplo muestra cómo deshabilitar el servicio de integración de búsqueda para un bloque.

[source, subs="specialcharacters,quotes"]
----
DELETE /test1?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== OBTENGA la solicitud de configuración de notificación de metadatos del bloque

La solicitud de configuración DE notificación DE metadatos GET Bucket permite recuperar el XML de configuración que se utiliza para configurar la integración de búsqueda de bloques individuales.

Para completar esta operación, debe tener el permiso s3:GetBucketMetadataNotification, o ser raíz de la cuenta.



=== Ejemplo de solicitud

Esta solicitud recupera la configuración de notificación de metadatos del bloque denominado `bucket`.

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== Respuesta

El cuerpo de la respuesta incluye la configuración de notificación de metadatos para el bloque. La configuración de notificaciones de metadatos permite determinar cómo se configura el bloque para la integración de búsquedas. Es decir, permite determinar a qué objetos se indexan y a qué extremos se envían los metadatos de sus objetos.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:_region:account-ID_:domain/_mydomain/myindex/mytype_</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
Cada configuración de notificación de metadatos incluye una o varias reglas. Cada regla especifica los objetos a los que se aplica y el destino al que StorageGRID debe enviar metadatos de objetos. Los destinos se deben especificar con el URN de un extremo de StorageGRID.

|===
| Nombre | Descripción | Obligatorio 


 a| 
MetadataNotificationConfiguration
 a| 
Etiqueta de contenedor para las reglas que se usan para especificar los objetos y el destino de las notificaciones de metadatos.

Contiene uno o más elementos Regla.
 a| 
Sí



 a| 
Regla
 a| 
Código de contenedor de una regla que identifica los objetos cuyos metadatos deben agregarse a un índice especificado.

Se rechazan las reglas con prefijos superpuestos.

Incluido en el elemento MetadataNotificationConfiguration.
 a| 
Sí



 a| 
ID
 a| 
Identificador único de la regla.

Incluido en el elemento Regla.
 a| 
No



 a| 
Estado
 a| 
El estado puede ser "activado" o "desactivado". No se toman medidas para las reglas que están desactivadas.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
Prefijo
 a| 
Los objetos que coinciden con el prefijo se ven afectados por la regla y sus metadatos se envían al destino especificado.

Para hacer coincidir todos los objetos, especifique un prefijo vacío.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
Destino
 a| 
Etiqueta de contenedor para el destino de una regla.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
No
 a| 
URN del destino donde se envían los metadatos del objeto. Debe ser URN de un extremo de StorageGRID con las siguientes propiedades:

* `es` debe ser el tercer elemento.
* El URN debe terminar con el índice y el tipo donde se almacenan los metadatos, en el formulario `domain-name/myindex/mytype`.


Los extremos se configuran con el administrador de inquilinos o la API de gestión de inquilinos. Tienen el siguiente formato:

* `arn:aws:es:_region:account-ID_:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


El punto final debe estar configurado antes de enviar el XML de configuración o la configuración fallará con un error 404.

El valor de urn se incluye en el elemento Destination.
 a| 
Sí

|===


=== Ejemplo de respuesta

El XML incluido entre  `<MetadataNotificationConfiguration></MetadataNotificationConfiguration>` tags muestra cómo se configura la integración con un extremo de integración de búsqueda para el bloque. En este ejemplo, los metadatos del objeto se envían a un índice de Elasticsearch llamado `current` y escriba named `2017` Que se aloja en un dominio de AWS llamado `records`.

[listing]
----
HTTP/1.1 200 OK
Date: Thu, 20 Jul 2017 18:24:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/11.0.0
x-amz-request-id: 3832973499
Content-Length: 264
Content-Type: application/xml

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix>2017</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/records/current/2017</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.Información relacionada
link:../tenant/index.html["Usar una cuenta de inquilino"]



== PUT bucket metadata notification Configuration

La solicitud de configuración de notificación DE metadatos DE PUT Bucket permite habilitar el servicio de integración de búsqueda para bloques individuales. El XML de configuración de notificación de metadatos que se proporciona en el cuerpo de la solicitud especifica los objetos cuyos metadatos se envían al índice de búsqueda de destino.

Para completar esta operación, debe tener el permiso s3:PutBucketMetadataNotification para un bloque o ser raíz de la cuenta.



=== Solicitud

La solicitud debe incluir la configuración de notificación de metadatos en el cuerpo de la solicitud. Cada configuración de notificación de metadatos incluye una o varias reglas. Cada regla especifica los objetos a los que se aplica y el destino al que StorageGRID debe enviar metadatos de objetos.

Los objetos se pueden filtrar según el prefijo del nombre del objeto. Por ejemplo, puede enviar metadatos de los objetos con el prefijo `/images` en un destino y objetos con el prefijo `/videos` a otro.

Las configuraciones que tienen prefijos superpuestos no son válidas y se rechazan cuando se envían. Por ejemplo, una configuración que incluía una regla para objetos con el prefijo `test` y una segunda regla para los objetos con el prefijo `test2` no se permitirá.

Los destinos se deben especificar con el URN de un extremo de StorageGRID. El extremo debe existir cuando se envía la configuración de notificación de metadatos o la solicitud falla como un `400 Bad Request`. El mensaje de error indica: `Unable to save the metadata notification (search) policy. The specified endpoint URN does not exist: _URN_.`

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
En la tabla se describen los elementos del XML de configuración de notificaciones de metadatos.

|===
| Nombre | Descripción | Obligatorio 


 a| 
MetadataNotificationConfiguration
 a| 
Etiqueta de contenedor para las reglas que se usan para especificar los objetos y el destino de las notificaciones de metadatos.

Contiene uno o más elementos Regla.
 a| 
Sí



 a| 
Regla
 a| 
Código de contenedor de una regla que identifica los objetos cuyos metadatos deben agregarse a un índice especificado.

Se rechazan las reglas con prefijos superpuestos.

Incluido en el elemento MetadataNotificationConfiguration.
 a| 
Sí



 a| 
ID
 a| 
Identificador único de la regla.

Incluido en el elemento Regla.
 a| 
No



 a| 
Estado
 a| 
El estado puede ser "activado" o "desactivado". No se toman medidas para las reglas que están desactivadas.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
Prefijo
 a| 
Los objetos que coinciden con el prefijo se ven afectados por la regla y sus metadatos se envían al destino especificado.

Para hacer coincidir todos los objetos, especifique un prefijo vacío.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
Destino
 a| 
Etiqueta de contenedor para el destino de una regla.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
No
 a| 
URN del destino donde se envían los metadatos del objeto. Debe ser URN de un extremo de StorageGRID con las siguientes propiedades:

* `es` debe ser el tercer elemento.
* El URN debe terminar con el índice y el tipo donde se almacenan los metadatos, en el formulario `domain-name/myindex/mytype`.


Los extremos se configuran con el administrador de inquilinos o la API de gestión de inquilinos. Tienen el siguiente formato:

* `arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


El punto final debe estar configurado antes de enviar el XML de configuración o la configuración fallará con un error 404.

El valor de urn se incluye en el elemento Destination.
 a| 
Sí

|===


=== Solicitar ejemplos

Este ejemplo muestra habilitar la integración de búsqueda de un bloque. En este ejemplo, los metadatos de objeto de todos los objetos se envían al mismo destino.

[source, subs="specialcharacters,quotes"]
----
PUT /test1?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix></Prefix>
        <Destination>
           <Urn>urn:sgws:es:::sgws-notifications/test1/all</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
En este ejemplo, metadatos de objeto para objetos que coinciden con el prefijo `/images` se envía a un destino, mientras que los metadatos de objetos de los objetos que coinciden con el prefijo `/videos` se envía a un segundo destino.

[source, subs="specialcharacters,quotes"]
----
PUT /graphics?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Images-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/images</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/es-domain/graphics/imagetype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Videos-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/videos</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-west-1:22222222:domain/es-domain/graphics/videotype</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.Información relacionada
link:../tenant/index.html["Usar una cuenta de inquilino"]



=== JSON generado por el servicio de integración de búsqueda

Al habilitar el servicio de integración de búsqueda para un bloque, se genera un documento JSON y se envía al extremo de destino cada vez que se agregan, actualizan o eliminan metadatos o etiquetas del objeto.

Este ejemplo muestra un ejemplo de JSON que se podría generar cuando un objeto con la clave `SGWS/Tagging.txt` se crea en un bloque llamado `test`. La `test` el bloque no tiene versiones, por lo que el `versionId` la etiqueta está vacía.

[listing]
----
{
  "bucket": "test",
  "key": "SGWS/Tagging.txt",
  "versionId": "",
  "accountId": "86928401983529626822",
  "size": 38,
  "md5": "3d6c7634a85436eee06d43415012855",
  "region":"us-east-1"
  "metadata": {
    "age": "25"
  },
  "tags": {
    "color": "yellow"
  }
}
----


=== Metadatos de objetos incluidos en las notificaciones de metadatos

En la tabla se enumeran todos los campos que se incluyen en el documento JSON que se envían al extremo de destino cuando la integración de búsqueda está habilitada.

El nombre del documento incluye el nombre del bloque, el nombre del objeto y el ID de versión, si existe.

|===
| Tipo | Nombre del elemento | Descripción 


 a| 
Información sobre bloques y objetos
 a| 
cucharón
 a| 
Nombre del bloque



 a| 
Información sobre bloques y objetos
 a| 
clave
 a| 
Nombre de clave de objeto



 a| 
Información sobre bloques y objetos
 a| 
ID de versión
 a| 
Versión de objeto, para objetos en bloques con versiones



 a| 
Información sobre bloques y objetos
 a| 
región
 a| 
Región de bloque, por ejemplo `us-east-1`



 a| 
Metadatos del sistema
 a| 
tamaño
 a| 
Tamaño del objeto (en bytes) visible para un cliente HTTP



 a| 
Metadatos del sistema
 a| 
md5
 a| 
Hash de objeto



 a| 
Metadatos del usuario
 a| 
metadatos
`_key:value_`
 a| 
Todos los metadatos de usuario del objeto, como pares clave-valor



 a| 
Etiquetas
 a| 
etiquetas
`_key:value_`
 a| 
Todas las etiquetas de objeto definidas para el objeto, como pares clave-valor

|===
*Nota:* para etiquetas y metadatos de usuario, StorageGRID pasa fechas y números a Elasticsearch como cadenas o como notificaciones de eventos S3. Para configurar Elasticsearch para interpretar estas cadenas como fechas o números, siga las instrucciones de Elasticsearch para la asignación dinámica de campos y para asignar formatos de fecha. Debe habilitar las asignaciones de campos dinámicos en el índice antes de configurar el servicio de integración de búsqueda. Una vez indizado un documento, no se pueden editar los tipos de campo del documento en el índice.



== OBTENGA la solicitud de uso del almacenamiento

La solicitud GET Storage Usage le indica la cantidad total de almacenamiento que está usando una cuenta y por cada bloque asociado con la cuenta.

La cantidad de almacenamiento utilizada por una cuenta y sus depósitos puede obtenerse mediante una solicitud DE SERVICIO GET modificada con el `x-ntap-sg-usage` parámetro de consulta. Se realiza un seguimiento del uso del almacenamiento en bloques de forma independiente de las solicitudes DE PUT y DELETE procesadas por el sistema. Es posible que haya algún retraso antes de que los valores de uso coincidan con los valores esperados en función del procesamiento de las solicitudes, especialmente si el sistema está sometido a cargas pesadas.

De forma predeterminada, StorageGRID intenta recuperar la información de uso con una coherencia global fuerte. Si no se puede lograr una coherencia global sólida, StorageGRID intenta recuperar la información de uso con una coherencia de sitio sólida.

Debe tener el permiso s3:ListAllMyBuckets o ser la raíz de la cuenta para completar esta operación.



=== Ejemplo de solicitud

[source, subs="specialcharacters,quotes"]
----
GET /?x-ntap-sg-usage HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== Ejemplo de respuesta

Este ejemplo muestra una cuenta que tiene cuatro objetos y 12 bytes de datos en dos bloques. Cada bloque contiene dos objetos y seis bytes de datos.

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 00:49:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/10.2.0
x-amz-request-id: 727237123
Content-Length: 427
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<UsageResult xmlns="http://s3.storagegrid.com/doc/2015-02-01">
<CalculationTime>2014-11-19T05:30:11.000000Z</CalculationTime>
<ObjectCount>4</ObjectCount>
<DataBytes>12</DataBytes>
<Buckets>
<Bucket>
<Name>bucket1</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
<Bucket>
<Name>bucket2</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
</Buckets>
</UsageResult>
----


=== Creación de versiones

Cada versión de objeto almacenada contribuirá a la `ObjectCount` y.. `DataBytes` valores en la respuesta. Los marcadores de borrado no se agregan a la `ObjectCount` total.

.Información relacionada
link:consistency-controls.html["Controles de consistencia"]



== Solicitudes de bloque obsoletas para cumplimiento de normativas heredadas

Es posible que deba utilizar la API DE REST de StorageGRID S3 para gestionar los bloques creados con la función de cumplimiento heredada.



=== Función de cumplimiento de normativas obsoleta

La función de cumplimiento de StorageGRID que estaba disponible en versiones anteriores de StorageGRID quedó obsoleta y se reemplazó por el bloqueo de objetos de S3.

Si anteriormente habilitó el ajuste de cumplimiento global, la opción de bloqueo de objetos S3 global se habilita automáticamente al actualizar a StorageGRID 11.5. Ya no se pueden crear nuevos bloques con la función de cumplimiento habilitada; sin embargo, según sea necesario, se puede utilizar la API DE REST de StorageGRID S3 para gestionar bloques existentes que cumplen las normativas.

link:s3-rest-api-supported-operations-and-limitations.html["Uso del bloqueo de objetos de S3"]

link:../ilm/index.html["Gestión de objetos con ILM"]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Base de conocimientos de NetApp: Cómo gestionar bloques heredados que cumplen con la normativa StorageGRID 11.5"]



=== Obsoleto: PONGA modificaciones de solicitud de cucharón para el cumplimiento

El elemento XML de SGCompliance está obsoleto. Anteriormente, podría incluir este elemento personalizado de StorageGRID en el cuerpo de solicitud XML opcional de SOLICITUDES PUT Bucket para crear un bloque compatible.


IMPORTANT: La función de cumplimiento de StorageGRID que estaba disponible en versiones anteriores de StorageGRID quedó obsoleta y se reemplazó por el bloqueo de objetos de S3.

link:s3-rest-api-supported-operations-and-limitations.html["Uso del bloqueo de objetos de S3"]

link:../ilm/index.html["Gestión de objetos con ILM"]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Base de conocimientos de NetApp: Cómo gestionar bloques heredados que cumplen con la normativa StorageGRID 11.5"]

Ya no se pueden crear bloques nuevos con el cumplimiento de normativas habilitado. Se devuelve el siguiente mensaje de error si intenta utilizar las modificaciones DE la solicitud PUT Bucket para cumplir con las normativas a fin de crear un nuevo bloque compatible:

[listing]
----
The Compliance feature is deprecated.
Contact your StorageGRID administrator if you need to create new Compliant buckets.
----
.Información relacionada
link:../ilm/index.html["Gestión de objetos con ILM"]

link:../tenant/index.html["Usar una cuenta de inquilino"]



=== Obsoleto: GET Bucket Compliance Request

La solicitud DE cumplimiento GET Bucket queda obsoleta. Sin embargo, puede seguir utilizando esta solicitud para determinar la configuración de cumplimiento actual para un bloque compatible heredado existente.


IMPORTANT: La función de cumplimiento de StorageGRID que estaba disponible en versiones anteriores de StorageGRID quedó obsoleta y se reemplazó por el bloqueo de objetos de S3.

link:s3-rest-api-supported-operations-and-limitations.html["Uso del bloqueo de objetos de S3"]

link:../ilm/index.html["Gestión de objetos con ILM"]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Base de conocimientos de NetApp: Cómo gestionar bloques heredados que cumplen con la normativa StorageGRID 11.5"]

Para completar esta operación, debe tener el permiso s3:GetBucketCompliance o ser la raíz de la cuenta.



==== Ejemplo de solicitud

Esta solicitud de ejemplo le permite determinar la configuración de cumplimiento para el bloque denominado `mybucket`.

[source, subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


==== Ejemplo de respuesta

En la respuesta XML, `<SGCompliance>` enumera la configuración de cumplimiento vigente para el bloque. Esta respuesta de ejemplo muestra la configuración de cumplimiento de un bloque en el que se conservará cada objeto durante un año (525,600 minutos), a partir del momento en que el objeto se ingiere en la cuadrícula. Actualmente, no existe ningún derecho legal en este segmento. Cada objeto se eliminará automáticamente después de un año.

[source, subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
|===
| Nombre | Descripción 


 a| 
RetentionPeriodonMinutes
 a| 
La duración del período de retención para los objetos que se añadió a este bloque, en minutos. El período de retención se inicia cuando el objeto se ingiere en la cuadrícula.



 a| 
LegalHold
 a| 
* Cierto: Este segmento está actualmente bajo un control legal. Los objetos de este segmento no se pueden eliminar hasta que se levante la retención legal, incluso si ha caducado su período de retención.
* Falso: Este segmento no está actualmente bajo un derecho. Los objetos de este bloque se pueden eliminar cuando expire su período de retención.




 a| 
Eliminación automática
 a| 
* True: Los objetos de este bloque se eliminarán automáticamente cuando expire su período de retención, a menos que el bloque se encuentre bajo una retención legal.
* False: Los objetos de este bloque no se eliminarán automáticamente cuando finalice el período de retención. Debe eliminar estos objetos manualmente si necesita eliminarlos.


|===


==== Respuestas de error

Si el bloque no se creó para ser compatible, el código de estado HTTP para la respuesta es `404 Not Found`, Con un código de error S3 de `XNoSuchBucketCompliance`.

.Información relacionada
link:../ilm/index.html["Gestión de objetos con ILM"]

link:../tenant/index.html["Usar una cuenta de inquilino"]



=== Obsoleto: PUT Bucket Compliance Request

La solicitud DE cumplimiento PUT Bucket queda obsoleta. Sin embargo, puede seguir utilizando esta solicitud para modificar la configuración de cumplimiento de un bloque compatible heredado existente. Por ejemplo, puede colocar un bloque existente en la retención legal o aumentar su período de retención.


IMPORTANT: La función de cumplimiento de StorageGRID que estaba disponible en versiones anteriores de StorageGRID quedó obsoleta y se reemplazó por el bloqueo de objetos de S3.

link:s3-rest-api-supported-operations-and-limitations.html["Uso del bloqueo de objetos de S3"]

link:../ilm/index.html["Gestión de objetos con ILM"]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Base de conocimientos de NetApp: Cómo gestionar bloques heredados que cumplen con la normativa StorageGRID 11.5"]

Debe tener el permiso s3:PutBucketCompliance o ser la raíz de la cuenta para completar esta operación.

Debe especificar un valor para cada campo de la configuración de cumplimiento al emitir una solicitud DE cumplimiento PUT Bucket.



==== Ejemplo de solicitud

Esta solicitud de ejemplo modifica la configuración de cumplimiento del bloque denominado `mybucket`. En este ejemplo, los objetos de `mybucket` ahora se conservará durante dos años (1,051,200 minutos) en lugar de un año, a partir del momento en que el objeto se ingiere en la cuadrícula. No existe ningún derecho legal en este segmento. Cada objeto se eliminará automáticamente después de dos años.

[source, subs="specialcharacters,quotes"]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization name_
Host: _host_
Content-Length: 152

<SGCompliance>
  <RetentionPeriodMinutes>1051200</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
|===
| Nombre | Descripción 


 a| 
RetentionPeriodonMinutes
 a| 
La duración del período de retención para los objetos que se añadió a este bloque, en minutos. El período de retención se inicia cuando el objeto se ingiere en la cuadrícula.

*Atención:* al especificar un nuevo valor para RetentionPeriodonMinutes, debe especificar un valor igual o mayor que el período de retención actual del cucharón. Una vez establecido el período de retención del segmento, no podrá disminuir dicho valor; sólo podrá aumentarlo.



 a| 
LegalHold
 a| 
* Cierto: Este segmento está actualmente bajo un control legal. Los objetos de este segmento no se pueden eliminar hasta que se levante la retención legal, incluso si ha caducado su período de retención.
* Falso: Este segmento no está actualmente bajo un derecho. Los objetos de este bloque se pueden eliminar cuando expire su período de retención.




 a| 
Eliminación automática
 a| 
* True: Los objetos de este bloque se eliminarán automáticamente cuando expire su período de retención, a menos que el bloque se encuentre bajo una retención legal.
* False: Los objetos de este bloque no se eliminarán automáticamente cuando finalice el período de retención. Debe eliminar estos objetos manualmente si necesita eliminarlos.


|===


==== Nivel de coherencia para la configuración de cumplimiento de normativas

Cuando se actualiza la configuración de cumplimiento de normativas para un bloque de S3 con una solicitud DE cumplimiento PUT Bucket, StorageGRID intenta actualizar los metadatos del bloque en el grid. De forma predeterminada, StorageGRID utiliza el nivel de consistencia *strong-global* para garantizar que todos los sitios de centros de datos y todos los nodos de almacenamiento que contienen metadatos de bloques tengan coherencia de lectura tras escritura para la configuración de cumplimiento modificada.

Si StorageGRID no puede alcanzar el nivel de consistencia *strong-global* debido a que un sitio de centro de datos o varios nodos de almacenamiento de un sitio no están disponibles, el código de estado HTTP de la respuesta es `503 Service Unavailable.`

Si recibe esta respuesta, debe ponerse en contacto con el administrador de grid para garantizar que los servicios de almacenamiento requeridos estén disponibles en Lo antes posible.. Si el administrador de grid no puede hacer que haya suficientes nodos de almacenamiento en cada sitio disponibles, el soporte técnico puede pedirle que vuelva a intentar la solicitud fallida forzando el nivel de consistencia de *sitio seguro*.


IMPORTANT: Nunca fuerce el nivel de consistencia de *sitio fuerte* para EL cumplimiento DE LA cuchara DE PUT a menos que usted haya sido dirigido a hacerlo por el soporte técnico y a menos que usted entienda las consecuencias potenciales de usar este nivel.

Cuando el nivel de consistencia se reduce a *sitio seguro*, StorageGRID garantiza que la configuración de cumplimiento actualizada tendrá coherencia de lectura tras escritura sólo para las solicitudes de cliente dentro de un sitio. Esto significa que el sistema StorageGRID podría tener temporalmente varias configuraciones incoherentes para este bloque hasta que todos los sitios y nodos de almacenamiento estén disponibles. La configuración incoherente puede dar como resultado un comportamiento inesperado y no deseado. Por ejemplo, si coloca un bloque bajo una retención legal y fuerza un nivel de coherencia más bajo, la configuración de cumplimiento anterior del bloque (es decir, la retención legal) puede seguir vigente en algunos centros de datos. Como resultado, los objetos que cree que están en retención legal se pueden eliminar cuando caduque su período de retención, ya sea por el usuario o por AutoDelete, si está activado.

Para forzar el uso del nivel de consistencia de *sitio fuerte*, vuelva a emitir la solicitud DE cumplimiento DE PUT Bucket e incluya el `Consistency-Control` Encabezado de solicitud HTTP, de la siguiente manera:

[listing]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Consistency-Control: strong-site
----


==== Respuestas de error

* Si el bloque no se creó para ser compatible, el código de estado HTTP para la respuesta es `404 Not Found`.
* Si `RetentionPeriodMinutes` En la solicitud es inferior al período de retención actual del bloque, el código de estado HTTP es `400 Bad Request`.


.Información relacionada
link:storagegrid-s3-rest-api-operations.html["Obsoleto: PONGA modificaciones de solicitud de cucharón para el cumplimiento"]

link:../tenant/index.html["Usar una cuenta de inquilino"]

link:../ilm/index.html["Gestión de objetos con ILM"]
