---
permalink: s3/support-for-s3-rest-api.html 
sidebar: sidebar 
keywords:  
summary: 'StorageGRID admite la API de simple Storage Service \(S3\), que se implementa como un conjunto de servicios web de transferencia de estado de representación \(REST\). La compatibilidad con la API REST de S3 permite conectar aplicaciones orientadas a los servicios desarrolladas para los servicios web S3 con un almacenamiento de objetos en las instalaciones que usa el sistema StorageGRID. Esto requiere cambios mínimos en el uso actual de llamadas API DE REST de S3 por parte de una aplicación cliente.' 
---
= Compatibilidad con la API REST de S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID admite la API de simple Storage Service (S3), que se implementa como un conjunto de servicios web de transferencia de estado de representación (REST). La compatibilidad con la API REST de S3 permite conectar aplicaciones orientadas a los servicios desarrolladas para los servicios web S3 con un almacenamiento de objetos en las instalaciones que usa el sistema StorageGRID. Esto requiere cambios mínimos en el uso actual de llamadas API DE REST de S3 por parte de una aplicación cliente.

* link:changes-to-s3-rest-api-support.html["Cambios en la compatibilidad con la API DE REST de S3"]
* link:supported-versions.html["Versiones compatibles"]
* link:support-for-storagegrid-platform-services.html["Soporte para servicios de plataforma StorageGRID"]

