---
permalink: monitor/comparing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: alerts, alarms, comparing alerts and alarms 
summary: Existen varias similitudes entre el sistema de alerta y el sistema de alarma heredado, pero el sistema de alerta ofrece ventajas significativas y es más fácil de usar. 
---
= Comparación de alertas y alarmas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existen varias similitudes entre el sistema de alerta y el sistema de alarma heredado, pero el sistema de alerta ofrece ventajas significativas y es más fácil de usar.

Consulte la siguiente tabla para obtener información sobre cómo realizar operaciones similares.

|===
|  | Alertas | Alarmas (sistema heredado) 


 a| 
¿Cómo puedo ver qué alertas o alarmas están activas?
 a| 
* Haga clic en el enlace *Alertas actuales* del Panel.
* Haga clic en la alerta en la página *Nodes* > *Overview*.
* Seleccione *Alertas* > *corriente*.


link:viewing-current-alerts.html["Ver las alertas actuales"]
 a| 
* Haga clic en el enlace *alarmas heredadas* del panel.
* Seleccione *Soporte* > *Alarmas (heredadas)* > *Alarmas actuales*.


link:viewing-legacy-alarms.html["Visualización de alarmas heredadas"]



 a| 
¿Qué hace que se active una alerta o una alerta?
 a| 
Las alertas se activan cuando una expresión Prometheus de una regla de alerta se evalúa como TRUE para la condición y duración de desencadenador específicas.

link:managing-alerts.html["Ver reglas de alerta"]
 a| 
Las alarmas se activan cuando un atributo StorageGRID alcanza un valor de umbral.

link:managing-alarms.html["Lógica de activación de alarmas (sistema heredado)"]



 a| 
Si se activa una alerta o alarma, ¿cómo puedo resolver el problema subyacente?
 a| 
Las acciones recomendadas para una alerta se incluyen en las notificaciones por correo electrónico y están disponibles en las páginas Alertas de Grid Manager.

Según sea necesario, se proporciona información adicional en la documentación de StorageGRID.

link:alerts-reference.html["Referencia de alertas"]
 a| 
Puede obtener información sobre una alarma haciendo clic en el nombre del atributo o puede buscar un código de alarma en la documentación de StorageGRID.

link:alarms-reference.html["Referencia de alarmas (sistema heredado)"]



 a| 
¿Dónde puedo ver una lista de alertas o alarmas que se han resuelto?
 a| 
* Haga clic en el enlace *Alertas resueltas recientemente* del Panel.
* Seleccione *Alertas* > *resuelto*.


link:viewing-resolved-alerts.html["Ver alertas resueltas"]
 a| 
Seleccione *Soporte* > *Alarmas (heredadas)* > *Alarmas históricas*.

link:managing-alarms.html["Revisión de las alarmas históricas y la frecuencia de las alarmas (sistema heredado)"]



 a| 
¿Dónde puedo gestionar la configuración?
 a| 
Seleccione *Alertas*. A continuación, utilice las opciones del menú Alertas.

link:managing-alerts.html["Gestión de alertas"]
 a| 
Seleccione *Soporte*. A continuación, utilice las opciones de la sección *Alarmas (heredadas)* del menú.

link:managing-alarms.html["Gestión de alarmas (sistema heredado)"]



 a| 
¿Qué permisos de grupo de usuarios necesito?
 a| 
* Cualquier persona que pueda iniciar sesión en Grid Manager puede ver las alertas actuales y resueltas.
* Debe tener el permiso Administrar alertas para gestionar las silencios, notificaciones de alerta y reglas de alerta.


link:../admin/index.html["Administre StorageGRID"]
 a| 
* Cualquier persona que pueda iniciar sesión en Grid Manager puede ver las alarmas heredadas.
* Debe tener el permiso Confirmar alarmas para confirmar alarmas.
* Debe tener tanto los permisos de configuración de página de topología de cuadrícula como de configuración de cuadrícula para gestionar las alarmas globales y las notificaciones por correo electrónico.


link:../admin/index.html["Administre StorageGRID"]



 a| 
¿Cómo puedo gestionar las notificaciones por correo electrónico?
 a| 
Seleccione *Alertas* > *Configuración de correo electrónico*.

*Nota:* debido a que las alarmas y alertas son sistemas independientes, la configuración de correo electrónico utilizada para las notificaciones de alarma y AutoSupport no se utiliza para las notificaciones de alerta. Sin embargo, puede utilizar el mismo servidor de correo para todas las notificaciones.

link:managing-alerts.html["Gestión de notificaciones de alerta"]
 a| 
Seleccione *Soporte* > *Alarmas (heredado)* > *Configuración de correo electrónico heredado*. link:managing-alarms.html["Configuración de notificaciones para alarmas (sistema heredado)"]



 a| 
¿Cómo se gestionan las notificaciones SNMP?
 a| 
Seleccione *Configuración* > *Supervisión* > *Agente SNMP*. link:using-snmp-monitoring.html["Uso de la supervisión de SNMP"]
 a| 
Seleccione *Configuración* > *Supervisión* > *Agente SNMP*. link:using-snmp-monitoring.html["Uso de la supervisión de SNMP"]

*Nota*: Las notificaciones SNMP no se envían para cada alarma o gravedad de alarma.

link:alarms-that-generate-snmp-notifications.html["Alarmas que generan notificaciones SNMP (sistema heredado)"]



 a| 
¿Cómo puedo controlar quién recibe notificaciones?
 a| 
. Seleccione *Alertas* > *Configuración de correo electrónico*.
. En la sección *destinatarios*, introduzca una dirección de correo electrónico para cada lista de correo electrónico o persona que deba recibir un correo electrónico cuando se produzca una alerta.


link:managing-alerts.html["Configurar notificaciones por correo electrónico para alertas"]
 a| 
. Seleccione *Soporte* > *Alarmas (heredado)* > *Configuración de correo electrónico heredado*.
. Crear una lista de correo.
. Seleccione *Notificaciones*.
. Seleccione la lista de correo.


link:managing-alarms.html["Creación de listas de correo para notificaciones de alarma (sistema heredado)"]

link:managing-alarms.html["Configuración de notificaciones por correo electrónico para alarmas (sistema heredado)"]



 a| 
¿Qué nodos administrador envían notificaciones?
 a| 
Un solo nodo Admin (el "'emisor preferido'").

link:../admin/index.html["Administre StorageGRID"]
 a| 
Un solo nodo Admin (el "'emisor preferido'").

link:../admin/index.html["Administre StorageGRID"]



 a| 
¿Cómo puedo suprimir algunas notificaciones?
 a| 
. Seleccione *Alertas* > *silencios*.
. Seleccione la regla de alerta que desea silenciar.
. Especifique una duración para el silencio.
. Seleccione la gravedad de la alerta que desea silenciar.
. Seleccione esta opción para aplicar el silencio a toda la cuadrícula, un solo sitio o un único nodo.


*Nota*: Si ha habilitado el agente SNMP, las silencios también suprimen las capturas SNMP e informan.

link:managing-alerts.html["Silenciar notificaciones de alerta"]
 a| 
. Seleccione *Soporte* > *Alarmas (heredado)* > *Configuración de correo electrónico heredado*.
. Seleccione *Notificaciones*.
. Seleccione una lista de correo y seleccione *Suprimir*.


link:managing-alarms.html["Suprimir notificaciones de alarma para una lista de correo (sistema heredado)"]



 a| 
¿Cómo puedo suprimir todas las notificaciones?
 a| 
Seleccione *Alertas* > *silencios*.luego, seleccione *todas las reglas*.

*Nota*: Si ha habilitado el agente SNMP, las silencios también suprimen las capturas SNMP e informan.

link:managing-alerts.html["Silenciar notificaciones de alerta"]
 a| 
. Seleccione *Configuración* > *Configuración del sistema* > *Opciones de pantalla*.
. Active la casilla de verificación *Suprimir notificación todo*.


*Nota*: La supresión de todo el sistema de notificaciones por correo electrónico también suprime los mensajes de correo electrónico AutoSupport activados por eventos.

link:managing-alarms.html["Supresión de las notificaciones por correo electrónico en todo el sistema"]



 a| 
¿Cómo puedo personalizar las condiciones y los desencadenantes?
 a| 
. Seleccione *Alertas* > *Reglas de alerta*.
. Seleccione una regla predeterminada para editar o seleccione *Crear regla personalizada*.


link:managing-alerts.html["Editar una regla de alerta"]

link:managing-alerts.html["Crear reglas de alerta personalizadas"]
 a| 
. Seleccione *Soporte* > *Alarmas (heredadas)* > *Alarmas globales*.
. Cree una alarma Global Custom para anular una alarma predeterminada o para supervisar un atributo que no tenga una alarma predeterminada.


link:managing-alarms.html["Creación de alarmas personalizadas globales (sistema heredado)"]



 a| 
¿Cómo puedo desactivar una alerta o alarma individual?
 a| 
. Seleccione *Alertas* > *Reglas de alerta*.
. Seleccione la regla y haga clic en *Editar regla*.
. Deseleccione la casilla de verificación *Activado*.


link:managing-alerts.html["Deshabilitar una regla de alerta"]
 a| 
. Seleccione *Soporte* > *Alarmas (heredadas)* > *Alarmas globales*.
. Seleccione la regla y haga clic en el icono Editar.
. Deseleccione la casilla de verificación *Activado*.


link:managing-alarms.html["Desactivación de una alarma predeterminada (sistema heredado)"]

link:managing-alarms.html["Desactivación de alarmas personalizadas globales (sistema heredado)"]

|===