---
permalink: monitor/generating-text-reports.html 
sidebar: sidebar 
keywords: reports, text 
summary: Los informes de texto muestran una representación textual de los valores de datos de atributos que ha procesado el servicio NMS. Puede generar informes en el sitio de un centro de datos, en el nodo de grid, en el componente o en el servicio. 
---
= Generación de informes de texto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los informes de texto muestran una representación textual de los valores de datos de atributos que ha procesado el servicio NMS. Puede generar informes en el sitio de un centro de datos, en el nodo de grid, en el componente o en el servicio.

.Lo que necesitará
* Debe iniciar sesión en Grid Manager mediante un explorador compatible.
* Debe tener permisos de acceso específicos.


.Acerca de esta tarea
Para los datos de atributos que se espera que cambien continuamente, el servicio NMS (en el origen) muestra estos datos de atributos a intervalos regulares. Para los datos de atributos que cambian con poca frecuencia (por ejemplo, datos basados en eventos como cambios de estado o de estado), se envía un valor de atributo al servicio NMS cuando cambia el valor.

El tipo de informe que se muestra depende del período de tiempo configurado. De forma predeterminada, se generan informes de texto agregados para períodos de tiempo superiores a una semana.

El texto gris indica que el servicio se ha reducido administrativamente durante el tiempo en que se realizó la muestra. El texto azul indica que el servicio estaba en un estado desconocido.

.Pasos
. Seleccione *Soporte* > *Herramientas* > *Topología de cuadrícula*.
. Seleccione *_grid node_* > *_component o Service_* > *Reports* > *Text*.
. Seleccione el atributo sobre el que desea informar en la lista desplegable *atributo*.
. Seleccione el número de resultados por página en la lista desplegable *resultados por página*.
. Para redondear los valores a un máximo de tres decimales (por ejemplo, para los atributos notificados como porcentajes), anule la selección de la casilla de verificación *datos brutos* .
. Seleccione el período de tiempo que desea generar el informe en la lista desplegable *Consulta rápida*.
+
Seleccione la opción Consulta personalizada para seleccionar un intervalo de tiempo específico.

+
El informe aparece después de unos momentos. Deje varios minutos para tabulación de intervalos de tiempo largos.

. Si ha seleccionado Consulta personalizada, debe personalizar el período de tiempo para informar introduciendo *Fecha de inicio* y *Fecha de finalización*.
+
Utilice el formato `YYYY/MM/DDHH:MM:SS` en hora local. Se requieren ceros a la izquierda para que coincidan con el formato. Por ejemplo, 2017/4/6 7:30:00 falla en la validación. El formato correcto es: 2017/04/06 07:30:00.

. Haga clic en *Actualizar*.
+
Después de unos momentos se genera un informe de texto. Deje varios minutos para tabulación de intervalos de tiempo largos. Según el tiempo establecido para la consulta, se muestra un informe de texto sin procesar o un informe de texto agregado.

. Si desea imprimir el informe, haga clic con el botón derecho del ratón y seleccione *Imprimir*, modifique cualquier configuración de impresora necesaria y haga clic en *Imprimir*.

