---
permalink: monitor/managing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: managing, alarms, alerts 
summary: El sistema de alertas StorageGRID se ha diseñado para informarle de los problemas operativos que requieren su atención. Según sea necesario, también puede utilizar el sistema de alarma anterior para supervisar el sistema. 
---
= Gestión de alertas y alarmas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema de alertas StorageGRID se ha diseñado para informarle de los problemas operativos que requieren su atención. Según sea necesario, también puede utilizar el sistema de alarma anterior para supervisar el sistema. Esta sección contiene las siguientes subsecciones:

* link:comparing-alerts-and-alarms.html["Comparación de alertas y alarmas"]
* link:managing-alerts.html["Gestión de alertas"]
* link:managing-alarms.html["Gestión de alarmas (sistema heredado)"]


StorageGRID incluye dos sistemas para informarle de cualquier problema.



== Sistema de alertas

El sistema de alertas está diseñado para ser su herramienta principal para supervisar cualquier problema que pueda producirse en el sistema StorageGRID. El sistema de alertas proporciona una interfaz fácil de usar para detectar, evaluar y resolver problemas.

Las alertas se activan en niveles de gravedad específicos cuando las condiciones de regla de alerta se evalúan como verdaderas. Cuando se activa una alerta, se realizan las siguientes acciones:

* Se muestra un icono de gravedad de alerta en el Panel de Grid Manager y aumenta el recuento de alertas actuales.
* La alerta se muestra en la ficha *Nodes* > *_node_* > *Overview*.
* Se envía una notificación por correo electrónico, suponiendo que se haya configurado un servidor SMTP y que se hayan proporcionado direcciones de correo electrónico para los destinatarios.
* Se envía una notificación de Protocolo simple de administración de red (SNMP), suponiendo que haya configurado el agente SNMP de StorageGRID.




== Sistema de alarma heredado

El sistema de alarma es compatible, pero se considera un sistema heredado. Al igual que las alertas, las alarmas se activan en niveles de gravedad específicos cuando los atributos alcanzan valores de umbral definidos. Sin embargo, a diferencia de las alertas, se activan muchas alarmas para los eventos que se pueden ignorar de forma segura, lo que podría dar lugar a un número excesivo de mensajes de correo electrónico o notificaciones SNMP.

Cuando se activa una alarma, se realizan las siguientes acciones:

* Se incrementa el recuento de alarmas antiguas en el panel.
* La alarma aparece en la página *Support* > *Alarms (Legacy)* > *Current Alarms*.
* Se envía una notificación por correo electrónico, suponiendo que ha configurado un servidor SMTP y una o más listas de correo.
* Es posible que se envíe una notificación de SNMP, suponiendo que haya configurado el agente SNMP de StorageGRID. (Las notificaciones SNMP no se envían para todas las alarmas ni para las gravedades de alarma).

