---
permalink: maintain/linux-adding-interfaces-to-existing-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, linux, adding interfaces, add interfaces, adding interface to node, add interface to node 
summary: Si desea añadir una interfaz a un nodo basado en Linux que no se instaló inicialmente, debe utilizar este procedimiento. 
---
= Linux: Añadir interfaces a un nodo existente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea añadir una interfaz a un nodo basado en Linux que no se instaló inicialmente, debe utilizar este procedimiento.

Si no configuró ADMIN_NETWORK_TARGET o CLIENT_NETWORK_TARGET en el archivo de configuración del nodo en el host Linux durante la instalación, utilice este procedimiento para añadir la interfaz. Para obtener más información sobre el archivo de configuración de nodos, consulte las instrucciones de instalación de StorageGRID para el sistema operativo Linux.

link:../rhel/index.html["Instale Red Hat Enterprise Linux o CentOS"]

link:../ubuntu/index.html["Instalar Ubuntu o Debian"]

Realiza este procedimiento en el servidor Linux que aloja el nodo que necesita la nueva asignación de red, no dentro del nodo. Este procedimiento solo añade la interfaz al nodo; se produce un error de validación si intenta especificar cualquier otro parámetro de red.

Para proporcionar información de direccionamiento, debe utilizar la herramienta Cambiar IP. Consulte la información sobre cómo cambiar la configuración de red de un nodo.

link:changing-nodes-network-configuration.html["Cambiar la configuración de red de un nodo"]

.Pasos
. Inicie sesión en el servidor Linux que aloja el nodo que necesita la nueva asignación de red.
. Edite el archivo de configuración del nodo en `/etc/storagegrid/nodes/_node-name_.conf`.
+

IMPORTANT: No especifique ningún otro parámetro de red o se producirá un error de validación.

+
.. Añada el nuevo destino de red.
+
[listing]
----
CLIENT_NETWORK_TARGET = bond0.3206
----
.. Opcional: Añada una dirección MAC.
+
[listing]
----
CLIENT_NETWORK_MAC = aa:57:61:07:ea:5c
----


. Ejecute el comando node validate: `sudo storagegrid node validate _node-name_`
. Resolver todos los errores de validación.
. Ejecute el comando node reload: `sudo storagegrid node reload _node-name_`


.Información relacionada
link:../rhel/index.html["Instale Red Hat Enterprise Linux o CentOS"]

link:../ubuntu/index.html["Instalar Ubuntu o Debian"]

link:changing-nodes-network-configuration.html["Cambiar la configuración de red de un nodo"]
