---
permalink: maintain/recovering-from-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, primary admin node failure 
summary: 'Debe completar un conjunto específico de tareas para recuperar el sistema después de un fallo en un nodo de administrador principal. El nodo de administración principal aloja el servicio nodo de administración de configuración \(CMN\) de la cuadrícula.' 
---
= Recuperación de fallos del nodo de administrador principal
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe completar un conjunto específico de tareas para recuperar el sistema después de un fallo en un nodo de administrador principal. El nodo de administrador principal aloja el servicio Configuration Management Node (CMN) de la cuadrícula.

.Acerca de esta tarea
Un nodo de administrador principal con fallos se debe reemplazar inmediatamente. El servicio nodo de gestión de configuración (CMN) del nodo de administración principal es responsable de emitir bloques de identificadores de objetos para la cuadrícula. Estos identificadores se asignan a los objetos a medida que se ingieren. Los objetos nuevos no se pueden procesar a menos que haya identificadores disponibles. La ingesta de objetos puede continuar mientras el CMN no está disponible porque el suministro de identificadores de aproximadamente un mes se almacena en caché en la cuadrícula. Sin embargo, después de que se agoten los identificadores almacenados en caché, no es posible añadir objetos nuevos.


IMPORTANT: Debe reparar o sustituir un nodo de administrador principal con fallos dentro de un mes aproximadamente, o bien el grid podría perder su capacidad de procesar objetos nuevos. El período de tiempo exacto depende de la tasa de ingesta de objetos: Si necesita una evaluación más precisa del plazo para el grid, póngase en contacto con el soporte técnico.

.Pasos
* link:copying-audit-logs-from-failed-primary-admin-node.html["Al copiar los registros de auditoría del nodo de administración principal con errores"]
* link:replacing-primary-admin-node.html["Reemplace el nodo de administrador principal"]
* link:configuring-replacement-primary-admin-node.html["Configurar el nodo de administrador principal de reemplazo"]
* link:restoring-audit-log-on-recovered-primary-admin-node.html["Restaurar el registro de auditoría en el nodo de administración primario recuperado"]
* link:resetting-preferred-sender-on-recovered-primary-admin-node.html["Restablecer el emisor preferido en el nodo de administración principal recuperado"]
* link:restoring-admin-node-database-primary-admin-node.html["Restaurar la base de datos de nodos de administrador cuando se recupera un nodo de administrador principal"]
* link:restoring-prometheus-metrics-primary-admin-node.html["Restaurar las métricas de Prometheus al recuperar un nodo de administración principal"]

