---
permalink: primer/storagegrid-attributes.html 
sidebar: sidebar 
keywords: attributes 
summary: Los atributos notifican valores y Estados para muchas de las funciones del sistema StorageGRID. Los valores de los atributos están disponibles para cada nodo de la cuadrícula, cada sitio y toda la cuadrícula. 
---
= Atributos de la StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los atributos notifican valores y Estados para muchas de las funciones del sistema StorageGRID. Los valores de los atributos están disponibles para cada nodo de la cuadrícula, cada sitio y toda la cuadrícula.

Los atributos StorageGRID se utilizan en varios lugares del Gestor de grid:

* *Página nodos*: Muchos de los valores mostrados en la página nodos son atributos StorageGRID. (Las métricas de Prometheus también se muestran en las páginas de nodos.)
* *Alarmas*: Cuando los atributos alcanzan valores de umbral definidos, las alarmas StorageGRID (sistema heredado) se activan a niveles de gravedad específicos.
* *Árbol de topología de cuadrícula*: Los valores de atributo se muestran en el árbol de topología de cuadrícula (*Soporte* > *Herramientas* > *Topología de cuadrícula*).
* *Eventos*: Los eventos del sistema se producen cuando ciertos atributos registran un error o condición de fallo para un nodo, incluidos errores como errores de red.




== Valores de atributo

Los atributos se notifican con el mejor esfuerzo y son aproximadamente correctos. Las actualizaciones de atributos se pueden perder en determinadas circunstancias, como el bloqueo de un servicio o el fallo y la reconstrucción de un nodo de cuadrícula.

Además, los retrasos de propagación pueden ralentizar la generación de informes de atributos. Los valores actualizados de la mayoría de los atributos se envían al sistema StorageGRID a intervalos fijos. Puede tardar varios minutos en que una actualización sea visible en el sistema, y se pueden notificar dos atributos que cambian más o menos simultáneamente en momentos ligeramente diferentes.

.Información relacionada
link:../monitor/index.html["Solución de problemas de  monitor"]
