---
permalink: sg5700/preparing-for-installation.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, install, installation, preparation, get ready, prepare 
summary: Para preparar la instalación de un dispositivo StorageGRID es necesario preparar el sitio y obtener todo el hardware, cables y herramientas necesarios. También debe recopilar información sobre las direcciones IP y la red. 
---
= Preparación de la instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para preparar la instalación de un dispositivo StorageGRID es necesario preparar el sitio y obtener todo el hardware, cables y herramientas necesarios. También debe recopilar información sobre las direcciones IP y la red.

.Pasos
* link:preparing-site-sg5700.html["Preparación del sitio (SG5700)"]
* link:unpacking-boxes-sg5700.html["Desembalaje de las cajas (SG5700)"]
* link:obtaining-additional-equipment-and-tools-sg5700.html["Obtención de equipos y herramientas adicionales (SG5700)"]
* link:web-browser-requirements.html["Requisitos del navegador web"]
* link:reviewing-appliance-network-connections-sg5700.html["Revisar las conexiones de red del dispositivo"]
* link:gathering-installation-information-sg5700.html["Recopilación de información de instalación (SG5700)"]

