---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, node, site, add, adding, expand, expansion 
summary: Puede seguir este procedimiento para agregar nodos de cuadrícula a sitios existentes o para agregar un sitio nuevo, pero no puede realizar ambos tipos de expansión al mismo tiempo. 
---
= Añadir nodos de grid a un sitio existente o añadir uno nuevo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede seguir este procedimiento para agregar nodos de cuadrícula a sitios existentes o para agregar un sitio nuevo, pero no puede realizar ambos tipos de expansión al mismo tiempo.

.Lo que necesitará
* Debe tener permisos raíz o de mantenimiento. Para obtener detalles, consulte la información sobre cómo controlar el acceso al sistema con grupos y cuentas de usuario de administración.
* Todos los nodos existentes en la cuadrícula deben estar activos y ejecutándose en todos los sitios.
* Deben completarse todos los procedimientos anteriores de ampliación, actualización, decomisionado o recuperación.
+

NOTE: Se le impide iniciar una expansión mientras otro procedimiento de expansión, actualización, recuperación o retirada activa está en curso. Sin embargo, si es necesario, puede pausar un procedimiento de retirada para iniciar una expansión.



.Pasos
. link:updating-subnets-for-grid-network.html["Actualización de subredes para la red de cuadrícula"]
. link:deploying-new-grid-nodes.html["Implementación de nuevos nodos de grid"]
. link:performing-expansion.html["Realización de la expansión"]

