---
permalink: troubleshoot/troubleshooting-delivery-platform-services-messages.html 
sidebar: sidebar 
keywords:  
summary: 'La alarma total de eventos (SMTT) se activa en Grid Manager si se envía un mensaje de servicio de plataforma a un destino que no puede aceptar los datos.' 
---
= Solución de problemas de la entrega de mensajes de servicios de la plataforma (alarma SMTT)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La alarma total de eventos (SMTT) se activa en Grid Manager si se envía un mensaje de servicio de plataforma a un destino que no puede aceptar los datos.

.Acerca de esta tarea
Por ejemplo, la carga de varias partes de S3 puede realizarse correctamente aunque no se pueda enviar el mensaje de notificación o replicación asociado al extremo configurado. O bien, puede no producirse un error en el mensaje de la replicación de CloudMirror si los metadatos son demasiado largos.

La alarma SMTT contiene un mensaje de último evento que dice: `Failed to publish notifications for _bucket-name object key_` para el último objeto cuya notificación falló.

Para obtener información adicional sobre la solución de problemas de los servicios de la plataforma, consulte las instrucciones para administrar StorageGRID. Es posible que necesite acceder al inquilino desde el Administrador de inquilinos para depurar un error de servicio de plataforma.

.Pasos
. Para ver la alarma, seleccione *Nodes* > *_site_* > *_grid node_* > *Events*.
. Ver último evento en la parte superior de la tabla.
+
Los mensajes de eventos también se muestran en la `/var/local/log/bycast-err.log`.

. Siga las instrucciones proporcionadas en el contenido de la alarma SMTT para corregir el problema.
. Haga clic en *Restablecer recuentos de eventos*.
. Notifique al inquilino los objetos cuyos mensajes de servicios de plataforma no se han entregado.
. Indique al inquilino que active la replicación o notificación fallida actualizando los metadatos o las etiquetas del objeto.


.Información relacionada
link:../admin/index.html["Administre StorageGRID"]

link:../tenant/index.html["Usar una cuenta de inquilino"]

link:../monitor/logs-files-reference.html["Referencia de archivos de registro"]

link:../monitor/resetting-event-counts.html["Restableciendo el número de eventos"]
